"""The sound vocabulary, planted defect by defect.

WHY THIS SET EXISTS. Audio is unusually easy to test badly, because almost
every observable near a sound effect is a proxy: the queue byte (consumed and
reset inside the same frame, so it reads $FF forever), a "the effect was
requested" flag, or a WAV whose RMS is dominated by the music the effect plays
under. A suite built on those passes on a rail that is completely silent. Each
plant below therefore switches off ONE mechanism in the most plausible way
available and leaves a ROM that still boots, still plays its music, and still
looks and mostly sounds like itself.

Two of the four are the sprint's OWN defects, replanted:

  sfx-mono-audio-mode        TAD's default audio mode is MONO
                             (tad-audio.inc:123) and nothing in the tree had
                             ever set it, so every panned queue call collapsed
                             to centre. This is the deleted line. It is the
                             most valuable plant here because the rail sounds
                             COMPLETELY NORMAL under it — every effect still
                             fires, at the right moment, with the right
                             instrument. Only the stereo image is gone, which
                             no assertion but a per-channel volume comparison
                             can see.

  sfx-skid-on-condition      the racer's off-road cue with its edge latch
                             removed. The skid still plays, at the right
                             moment, with the right sound; it simply re-keys
                             every frame the kart is on grass. A test that
                             asked "is the skid audible" stays GREEN under
                             this, which is exactly why the case that catches
                             it counts ONSETS instead.

NOT PLANTED, deliberately: the DECREASE-mode GAIN defect (five effects that
compiled, queued, keyed on and stayed at ENVX 0). It lives in
assets/audio/sound-effects.txt, which `make` does not compile — the ca65
export is checked in and regenerated by a manual Rust step — so patching it
would leave every ROM byte-identical and the harness would correctly report a
plant that changed nothing. The audibility cases guard that class instead, and
`sfx-laser-never-queued` is here to prove those cases are not vacuous.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from falsify import Plant                                   # noqa: E402

SUPERFORGE = Path(__file__).resolve().parent.parent.parent
SHMUP_MAIN = SUPERFORGE / "game" / "shmup" / "main.asm"
SHMUP_PLAY = SUPERFORGE / "game" / "shmup" / "scenes" / "play.asm"
RACE = SUPERFORGE / "game" / "racer" / "scenes" / "race.asm"
CFG = SUPERFORGE / "vendor" / "rom" / "lorom_512k.cfg"
CFG64 = SUPERFORGE / "vendor" / "rom" / "lorom_64k.cfg"
SAU_MAIN = SUPERFORGE / "game" / "boss_saucer" / "main.asm"
SAU_ARENA = SUPERFORGE / "game" / "boss_saucer" / "scenes" / "arena.asm"
OVERWORLD = SUPERFORGE / "game" / "rpg" / "scenes" / "overworld.asm"

T = "tests/test_sfx_vocabulary.py::"
Q = "tests/test_sfx_queue.py::"

PLANTS = [
    Plant(
        id="sfxq-queue-bypassed",
        file=SAU_ARENA,
        old="""    jsr sf_sfx_queue                ; ...heard from where the ship is""",
        new="""    jsr Tad_QueuePannedSoundEffect  ; PLANT: straight to the one-deep API""",
        artifact=SUPERFORGE / "build" / "boss_saucer.sfc",
        build=["boss_saucer"],
        tests=[Q + "test_both_cues_reach_the_driver",
               Q + "test_both_cues_are_audible"],
        why="THE DEFECT THE QUEUE EXISTS FOR, restored at one call site. The "
            "gun goes straight to TAD's one-deep API again, so a shot fired on "
            "the beam's ignition frame loses the slot to beam_fire (id 3 beats "
            "id 6) and a real bullet flies in silence. Nothing else changes: "
            "the bullet still spawns, still travels, still kills, and the beam "
            "still fires — which is exactly why this went unnoticed before it "
            "was forced. The collision PRECONDITION case must stay GREEN under "
            "this plant, and does; only the two cases that count deliveries "
            "and per-voice onsets can see it.",
    ),
    Plant(
        id="sfxq-reset-dropped",
        file=SAU_MAIN,
        old="""    jsr sf_sfx_reset                ; the ring holds power-on garbage until this""",
        new="""                                    ; PLANT: no reset — the ring boots dirty""",
        artifact=SUPERFORGE / "build" / "boss_saucer.sfc",
        build=["boss_saucer"],
        tests=[Q + "test_the_ring_boots_empty"],
        why="POWER-ON FIDELITY (CLAUDE.md rule 5), on a ring rather than a "
            "framebuffer. RAM is random at boot and the harness runs ROMs that "
            "way deliberately, so an unreset head/count indexes and drains "
            "garbage from the first frame. It is a one-line omission in a boot "
            "block — the most plausible way this comes back — and it is "
            "invisible on any emulator that zero-fills, which is the whole "
            "reason the house rule exists.",
    ),
    Plant(
        id="sfx-bank1-alignment-dropped",
        file=CFG,
        old="""    BANK1:      load = ROM1,  type = ro,  optional = yes, align = $4000;""",
        new="""    BANK1:      load = ROM1,  type = ro,  optional = yes;""",
        artifact=SUPERFORGE / "build" / "boss_saucer.sfc",
        build=["boss_saucer"],
        expect="build-fails",
        build_names="drifted from allocator claim",
        tests=[],
        why="THE ONE LINE HOLDING THE HALF-WINDOW CLAIM TOGETHER. `tad_export` "
            "reserves 16,384 B but the export's real segment content is 8,752 B, "
            "so without this alignment ld65 packs BANK1 immediately behind it "
            "(~$01A230) while the allocator emitted $01C000 for the blobs it "
            "put in the same window. Every blob would then be read from the "
            "wrong address — the silent-corruption shape this repo's .incbin "
            "asserts exist for. This plant proves those asserts still catch it: "
            "the build must FAIL, by name, rather than produce a ROM. It is an "
            "`expect=build-fails` plant because there is no ROM to test.\n"
            "It BUILT boss_saucer, not room: room moved to lorom_64k.cfg when "
            "its allocation fitted one window, so a plant patching the 512 KB "
            "cfg and building room tested nothing. The harness reported that "
            "as TEST-BLIND the first run after the move — a plant going quiet "
            "is the same class of rot as a test going quiet.",
    ),
    Plant(
        id="sfxq-bank1-align-dropped-64k",
        file=CFG64,
        old="""    BANK1:      load = ROM1,  type = ro,  optional = yes, align = $4000;""",
        new="""    BANK1:      load = ROM1,  type = ro,  optional = yes;""",
        artifact=SUPERFORGE / "build" / "room.sfc",
        build=["room"],
        expect="build-fails",
        build_names="drifted from allocator claim",
        tests=[],
        why="The SAME load-bearing alignment, in the OTHER config. Five rails "
            "link through lorom_64k.cfg now, so the 512 KB plant above no "
            "longer covers them at all — and an alignment that is only "
            "checked in one of the two files it lives in is checked by "
            "accident. Same mechanism, same loud refusal, different cart.",
    ),
    Plant(
        id="sfx-mono-audio-mode",
        file=SHMUP_MAIN,
        old="""    lda #TadAudioMode::STEREO
    sta Tad_audioMode
    lda #Song::slice_b_song""",
        new="""    lda #Song::slice_b_song""",
        artifact=SUPERFORGE / "build" / "shmup.sfc",
        build=["shmup"],
        tests=[T + "test_explosion_pans_to_the_fighter_that_died"],
        why="THE DEFECT THIS SPRINT SHIPPED AND THEN FOUND. TAD defaults to "
            "MONO and the tree had never set the mode, so the driver collapsed "
            "every channel to centre and each panned queue call cost cycles to "
            "achieve nothing. It is a one-line deletion in a boot block, which "
            "is exactly how it would come back — and under it the rail is "
            "indistinguishable by ear from a working one except for the stereo "
            "image, so only a per-channel volume comparison can fail.",
    ),
    Plant(
        id="sfx-explosion-pan-constant",
        file=SHMUP_PLAY,
        old="""    lda z:US_BX
    lsr a                       ; 256-px screen -> TAD's 0..128 pan
    tax""",
        new="""    lda #64                     ; PLANT: centre, whatever died where
    tax""",
        artifact=SUPERFORGE / "build" / "shmup.sfc",
        build=["shmup"],
        tests=[T + "test_explosion_pans_to_the_fighter_that_died"],
        why="The other half of the panning claim, and the plausible one: the "
            "call is still PANNED, the plumbing all works, the pan is simply "
            "not read from the thing that died. A kill anywhere on screen is "
            "heard dead centre. Everything else about the rail is untouched, "
            "so only the case that drives the ship to OPPOSITE SIDES and "
            "demands the balance move both ways can see it.",
    ),
    Plant(
        id="sfx-skid-on-condition",
        file=RACE,
        old="""    lda f:US_OFFR_LONG
    bne @done                       ; already off it: this is not a crossing
    lda #1
    sta f:US_OFFR_LONG""",
        new="""    lda #1                          ; PLANT: no edge test at all
    sta f:US_OFFR_LONG""",
        artifact=SUPERFORGE / "build" / "racer.sfc",
        build=["racer"],
        tests=[T + "test_skid_fires_on_the_CROSSING_not_every_frame"],
        why="The latch removed, which is how the cue would have been written "
            "if nobody had thought about cadence. The skid still plays, on the "
            "right surface, with the right sound — it re-keys ~60 times a "
            "second while the kart is on grass. `test_skid_is_audible` stays "
            "GREEN under this plant and must; the onset count is the only "
            "assertion that separates a crossing from a condition.",
    ),
    Plant(
        id="sfx-rpg-cue-per-frame",
        file=OVERWORLD,
        old="""    tax                             ; ...and the travel count for advance_px
    lda z:US_TS_STEP
    sec""",
        new="""    tax                             ; ...and the travel count for advance_px
    lda #SFX::footstep              ; PLANT: one per FRAME of travel
    jsr sfx_q
    lda z:US_TS_STEP
    sec""",
        artifact=SUPERFORGE / "build" / "rpg.sfc",
        build=["rpg"],
        tests=[T + "test_rpg_footstep_is_one_per_tile_not_one_per_frame"],
        why="THE `footstep while walking` MISTAKE, put where it would actually "
            "be written: walk_tick's spend path, which runs on every frame the "
            "avatar is travelling. The step then rings continuously instead of "
            "once per tile — measured, 84% of walking frames live against 19% "
            "healthy. An earlier version of this plant moved the cue to the "
            "step ATTEMPT instead, and the harness reported it TEST-BLIND: the "
            "slide gate limits how often try_step is reached, so that defect "
            "barely changed the output (27% vs 19%) and no honest bound could "
            "separate it. Its real lesson was about the ASSERTION — onsets "
            "FALL under a per-frame cue on an interruptible one-channel "
            "effect, because it restarts a voice that never goes silent — and "
            "that is why the case now reads live fraction.",
    ),
    Plant(
        id="sfx-laser-never-queued",
        file=SHMUP_PLAY,
        old="""    lda #SFX::laser
    jmp shm_sfx""",
        new="""    rts                         ; PLANT: the gun fires in silence""",
        artifact=SUPERFORGE / "build" / "shmup.sfc",
        build=["shmup"],
        tests=[T + "test_laser_is_audible"],
        why="The control for the audibility cases. Those assert on a KEYED "
            "voice with a live envelope specifically because five effects "
            "once compiled, queued and keyed on while ENVX stayed 0 — and an "
            "audibility case that cannot go red would have passed on all five. "
            "The bullet still spawns, flies and kills under this plant: only "
            "the sound is gone.",
    ),
]
