"""The rom-claim BACKING gate (docs/37) — the target, the rule, the limits.

WHAT THIS GATE IS FOR. A `rom` claim reserves bytes; it does not put any there.
The allocator packs it and emits `ES_R_<NAME>_{BANK,ADDR,OFF,SIZE}`, and the
claim site in ASM ties its `.incbin` to those symbols with
`.assert ^label = ES_R_<NAME>_BANK` — so a claim DRIFTING away from its data is
refused at assembly time. Nothing ever asked the other question: does the claim
have any data at all.

The bug that proves it matters is not hypothetical. rgb_gradient's `grad_tabs`
during an earlier breaker build (2026-08-02) was generated by its asset tool,
prerequisited in the Makefile and packed by the allocator, and **no .asm file
ever included it**. Three HDMA channels streamed the neighbouring blob's bytes
as COLDATA. The only symptom was a missing backdrop wash, and `make register`,
`no_literals`, `width-check`, the allocator's own packing and the full pytest
suite were all green.

TWO LAYERS, BOTH TESTED, following tests/test_make_gates.py's discipline: the
`make rom-unbacked` TARGET (where the wiring lives — the two arms, the greps,
the polarity) and the RULE inside `no_literals` (where the semantics live).

WHAT PINS THE TEETH IS A PAIR, NOT EITHER TEST ALONE. A gate that refuses
everything and a gate that refuses nothing are both useless, and each passes
one half of the pair:

  * `test_target_passes_on_the_real_fixture` fails a refuse-everything gate;
  * `test_target_goes_RED_when_the_rule_is_removed` fails a refuse-nothing one.

Together they force the verdict to be a function of the tree.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

SUPERFORGE = Path(__file__).resolve().parent.parent
FIXTURE = SUPERFORGE / "tests" / "fixtures" / "rom_backing"
ALLOC = SUPERFORGE / "allocator"

sys.path.insert(0, str(ALLOC))
import no_literals  # noqa: E402
import schemas      # noqa: E402

# The target tests run whole gates over the live tree and one plants into
# allocator/no_literals.py, so they take the repo lock the other whole-gate
# module takes (tests/conftest.py).
pytestmark = pytest.mark.usefixtures("repo_tree_lock")


def make(*args) -> subprocess.CompletedProcess:
    """A target exactly as CI, tools/setup.sh and a human invoke it.

    MAKEFLAGS cleared for the reason tests/test_make_gates.py states: under
    `make test` these become recursive makes and would otherwise inherit any
    flag the outer invocation carried.
    """
    env = {k: v for k, v in os.environ.items()
           if k not in ("MAKEFLAGS", "MFLAGS", "MAKELEVEL")}
    return subprocess.run(["make", *args], cwd=SUPERFORGE,
                          capture_output=True, text=True, env=env)


def gate(map_path: Path, *files) -> subprocess.CompletedProcess:
    """Positional args pass straight through, so a test can hand in a flag
    (`--partial-files`) as well as paths."""
    return subprocess.run(
        [sys.executable, str(ALLOC / "no_literals.py"), "--map", str(map_path),
         *[str(f) for f in files]],
        cwd=SUPERFORGE, capture_output=True, text=True)


@pytest.fixture(scope="module")
def fixture_map(tmp_path_factory) -> Path:
    out = tmp_path_factory.mktemp("romgate")
    r = subprocess.run(
        [sys.executable, str(ALLOC / "allocate.py"),
         "--game", str(FIXTURE), "--out", str(out)],
        cwd=SUPERFORGE, capture_output=True, text=True)
    assert r.returncode == 0, f"fixture allocation failed:\n{r.stdout}{r.stderr}"
    return out / "symbol_map.json"


# --------------------------------------------------------------------------
# make rom-unbacked — the target's teeth
# --------------------------------------------------------------------------

def test_target_passes_on_the_real_fixture():
    """Healthy repo: the control arm is accepted and the violation refused.

    Half the pair. This one fails a gate that refuses everything — including
    one that refuses the control arm — so a green violation arm cannot be
    reached by a rule with no discrimination in it.
    """
    r = make("rom-unbacked")
    assert r.returncode == 0, (
        f"make rom-unbacked failed on the real tree:\n{r.stdout}\n{r.stderr}")
    assert "rom-unbacked OK" in r.stdout


def test_target_goes_RED_when_the_rule_is_removed(tmp_path):
    """THE plant. De-teeth the rule; `make rom-unbacked` must now fail.

    The other half of the pair, and the only evidence that can distinguish a
    verdict from a constant. `make toy-bad` shipped for a day exiting non-zero
    on every path, and seven consumers read only that status; a gate nobody has
    seen fail is not a gate.

    Plants into allocator/no_literals.py itself rather than into the fixture,
    because the fixture is the INPUT the gate reads — removing its claim sites
    is what the violation arm already does. What is unproven without this test
    is that the RULE, not the fixture, produces the verdict. Restored in a
    finally, and the module holds the repo lock.
    """
    src = ALLOC / "no_literals.py"
    original = src.read_text()
    call = "        all_findings += scan_rom_backing(paths, raw_map, map_path, stats, root)"
    assert call in original, "the plant site moved — update this test"
    try:
        src.write_text(original.replace(call, "    pass  # DE-TEETHED (test)"))
        r = make("rom-unbacked")
    finally:
        src.write_text(original)
    assert r.returncode != 0, (
        "make rom-unbacked SUCCEEDED with the backing rule removed — the "
        f"target's status is a constant, not a verdict:\n{r.stdout}\n{r.stderr}")
    assert "no teeth" in r.stdout


# --------------------------------------------------------------------------
# the rule — what BACKED means
# --------------------------------------------------------------------------

def test_backed_arm_accepted(fixture_map):
    r = gate(fixture_map, FIXTURE / "main_backed.asm")
    assert r.returncode == 0, r.stderr
    # the census is part of the contract: exemptions stay counted, in the open
    assert "rom backing: 4 claim(s) (3 via an .incbin claim site, 1 via a " \
           "declared backed_by; credited from 1/1 scanned file(s)" in r.stdout


def test_unbacked_arm_refused_naming_every_missing_claim(fixture_map):
    r = gate(fixture_map, FIXTURE / "main_unbacked.asm")
    assert r.returncode == 1
    assert "ROM CLAIM UNBACKED" in r.stderr
    for sym in ("ES_R_FIXTURE_BLOB'", "ES_R_FIXTURE_TILES_T0'",
                "ES_R_FIXTURE_TILES_T1'"):
        assert sym in r.stderr, f"{sym} not named in the refusal"
    # the message has to be actionable: it names the claim, the feature, the
    # size, the emitted symbols and BOTH ways to fix it
    assert "engine:blob" in r.stderr and "256 B" in r.stderr
    assert "ES_R_FIXTURE_BLOB_BANK" in r.stderr
    assert "backed_by" in r.stderr


def test_declared_backed_by_is_honoured_on_both_arms(fixture_map):
    """The escape hatch is not swept up with the findings around it.

    `fixture_extern` has no claim site in EITHER main. If the hatch were read
    only on the passing arm, the violation arm would report a claim that is
    legitimately backed out of scope — the tad_export shape, and the one way
    this gate could make the tree worse than no gate.
    """
    for arm in ("main_backed.asm", "main_unbacked.asm"):
        r = gate(fixture_map, FIXTURE / arm)
        assert "ES_R_FIXTURE_EXTERN" not in r.stderr, (
            f"{arm}: the backed_by-declared claim was reported as unbacked")


def test_templated_claim_site_credits_its_chunks(fixture_map):
    """`.repeat` + `.sprintf` is the ONLY claim-site shape a bank_tiled claim
    can have — its chunk symbols exist nowhere as text. 12 chunk placements in
    the live tree (microzero 12, probe_colmap 8 of the same) depend on this.
    """
    lines = (FIXTURE / "main_backed.asm").read_text().splitlines()
    matchers, _ = no_literals._rom_backing_refs(lines)
    for sym in ("ES_R_FIXTURE_TILES_T0", "ES_R_FIXTURE_TILES_T1"):
        assert any(m(sym + "_BANK") for m in matchers), sym
    # ...and it does not credit a DIFFERENT claim that merely looks similar
    assert not any(m("ES_R_OTHER_TILES_T0_BANK") for m in matchers)


def test_declaration_block_is_narrow_enough_to_be_teeth(fixture_map, tmp_path):
    """A neighbour's `.assert`s must not credit a claim whose `.incbin` is the
    missing one.

    This is the harder half of the real bug's shape and the reason the block is
    bounded by labels rather than by a line radius: with the label and both
    `.assert`s left in place and only the `.incbin` deleted, **ca65 itself
    accepts the file** — the label lands at the claim's address either way, so
    the drift asserts still pass. Only a presence check can see it.
    """
    src = (FIXTURE / "main_backed.asm").read_text()
    planted = tmp_path / "main_incbin_only_gone.asm"
    planted.write_text(
        "\n".join(l for l in src.splitlines()
                  if '.incbin "fixture_blob.bin"' not in l) + "\n")
    r = gate(fixture_map, planted)
    assert r.returncode == 1
    assert "ES_R_FIXTURE_BLOB'" in r.stderr


def test_partial_files_skips_and_SAYS_it_skipped(fixture_map):
    """The opt-out for a caller that hands a SUBSET of a composition's ASM.

    The rom-backing pass is the only whole-composition check here, and a subset
    cannot answer it — the reg-gate plant tests hand one planted file a whole
    game's map, and every claim would read as unbacked. Opt-OUT, not opt-in, so
    the six Makefile invocations that gate real ROMs get the check by default
    and a partial caller has to say it is partial.

    The half that matters as much as the skip: the summary must SAY SKIPPED. A
    silent skip prints "clean" about a check that never ran, which is the
    toothless-gate shape `no_literals`' own summary line was rewritten to
    stop.
    """
    r = gate(fixture_map, "--partial-files", FIXTURE / "main_unbacked.asm")
    assert r.returncode == 0, r.stderr
    assert "rom backing: SKIPPED" in r.stdout
    assert "ROM CLAIM UNBACKED" not in r.stderr
    # ...and without the flag the SAME invocation is refused, so the flag is
    # doing the work and the arm is not passing for some other reason
    assert gate(fixture_map, FIXTURE / "main_unbacked.asm").returncode == 1


# --------------------------------------------------------------------------
# the escape hatch's own discipline
# --------------------------------------------------------------------------

def test_empty_backed_by_is_refused_by_the_schema(tmp_path):
    """An exemption that need not say why is a quiet way to turn the rule off.

    Same convention as `; REG-LINT: ok — <reason>` and `; WIDTH-LINT: ok —
    <reason>`, enforced where the declaration is parsed rather than where it is
    read, so it cannot be smuggled past a gate that happens not to run.
    """
    p = tmp_path / "feature.toml"
    p.write_text('name = "x"\nrole = "blob"\n\n'
                 '[[claims.rom]]\nname = "y"\nbytes = 16\nbacked_by = "  "\n')
    sub = schemas.load_substrate(ALLOC / "substrate.toml")
    with pytest.raises(schemas.SchemaError) as e:
        schemas.load_feature(p, sub)
    assert "backed_by" in str(e.value) and "empty" in str(e.value)


def test_backed_by_reaches_the_symbol_map(tmp_path):
    """The gate reads the MAP, not feature.toml — so the declaration has to
    survive the allocator. Emitted on rom placements only; a `backed_by` key on
    40 non-rom placements reads like a field someone forgot to fill."""
    out = tmp_path / "m"
    r = subprocess.run(
        [sys.executable, str(ALLOC / "allocate.py"),
         "--game", str(FIXTURE), "--out", str(out)],
        cwd=SUPERFORGE, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    d = json.loads((out / "symbol_map.json").read_text())
    roms = {p["sym"]: p for p in d["globals"] if p["class"] == "rom"}
    assert roms["ES_R_FIXTURE_EXTERN"]["backed_by"].strip()
    assert roms["ES_R_FIXTURE_BLOB"]["backed_by"] == ""
    assert all("backed_by" not in p for p in d["globals"] if p["class"] != "rom")


# --------------------------------------------------------------------------
# the live tree
# --------------------------------------------------------------------------

@pytest.mark.parametrize("game,mapdir", [
    ("game/microzero", "build/mz"), ("game/room", "build/rm"),
    ("game/breaker", "build/bk")])
def test_every_shipping_claim_is_backed(game, mapdir, tmp_path):
    """The in-tree guard. Regenerates each game's map into tmp_path and runs
    the gate over the same file set the Makefile passes, so it cannot pass by
    reading a stale map the build left behind."""
    out = tmp_path / "m"
    r = subprocess.run(
        [sys.executable, str(ALLOC / "allocate.py"), "--game", game,
         "--features-dir", "engine/features", "--out", str(out)],
        cwd=SUPERFORGE, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    files = ([SUPERFORGE / game / "main.asm"]
             + sorted((SUPERFORGE / game / "scenes").glob("*.asm"))
             + sorted((SUPERFORGE / "engine" / "features").glob("*/*.asm")))
    g = gate(out / "symbol_map.json", *files)
    assert g.returncode == 0, g.stderr
    assert "ROM CLAIM UNBACKED" not in g.stderr


# --------------------------------------------------------------------------
# the claim-site SHAPES the scanner has to read
# --------------------------------------------------------------------------

def _refs(text: str):
    return no_literals._rom_backing_refs(text.splitlines())[0]


def _credits(text: str, sym: str) -> bool:
    ms = _refs(text)
    return any(m(sym) or any(m(sym + s) for s in no_literals.ROM_SYM_SUFFIXES)
               for m in ms)


def test_label_on_the_incbin_line_is_read():
    """`font_bin: .incbin "x.bin"` is a claim site, not an invisible line.

    a later review. The anchor used to be `^\\s*\\.incbin`, so this shape produced
    no block and no refs at all: the claim read UNBACKED while its claim site
    sat right there, and the refusal told the author to add the label, the
    `.incbin` and the `.assert` they already had.
    """
    one_line = (
        '.segment "BANK1"\n'
        'a_bin: .incbin "a.bin"\n'
        '.assert ^a_bin = ES_R_A_BANK, error, "drift"\n')
    assert _credits(one_line, "ES_R_A")


def test_same_line_label_does_not_widen_the_block_backwards():
    """The narrowness survives the anchor fix.

    A label on the `.incbin` line means the block STARTS there. Walking
    backwards from it would swallow the preceding blob's `.assert`s — the
    wide-window weakening the block bound exists to prevent — so `ES_R_PREV`
    must NOT be credited by its neighbour when its own `.incbin` is gone.
    """
    src = (
        '.segment "BANK1"\n'
        'prev_bin:\n'                        # its .incbin is DELETED
        '.assert ^prev_bin = ES_R_PREV_BANK, error, "drift"\n'
        'next_bin: .incbin "next.bin"\n'
        '.assert ^next_bin = ES_R_NEXT_BANK, error, "drift"\n')
    assert _credits(src, "ES_R_NEXT")
    assert not _credits(src, "ES_R_PREV"), (
        "the same-line label form walked backwards and let a neighbour's "
        "asserts credit a claim whose own .incbin is missing")


def test_the_vendored_TAD_export_shape_is_readable():
    """That shape is in this tree, in a generated file, today.

    `assets/audio/export/tad_audio_data.asm` is outside the no_literals scope
    (it is `tad_export`'s declared `backed_by`), so nothing breaks while it
    stays there. This pins that the scanner could read it the day any
    generated unit of that shape IS brought inside the scope — which is the
    difference between the fix and a comment saying the fix would be nice.
    """
    real = (SUPERFORGE / "assets" / "audio" / "export" / "tad_audio_data.asm")
    line = next(l for l in real.read_text().splitlines()
                if ".incbin" in l and "tad_audio_data.bin" in l)
    assert ":" in line.split(".incbin")[0], (
        f"the generator's shape changed — this test's subject is a label on "
        f"the .incbin LINE: {line!r}")
    assert no_literals.INCBIN_RE.match(line), (
        f"the scanner cannot see the shape the TAD generator emits: {line!r}")


def test_asserts_before_the_incbin_are_accepted():
    """the doc said this shape was refused; it is not, and should
    not be. The block is bounded by the LABEL, so everything between that label
    and the next boundary is the same claim site whichever side of the
    `.incbin` it sits on. Pinned so the doc and the behaviour cannot drift
    apart again in either direction."""
    src = (
        '.segment "BANK1"\n'
        'a_bin:\n'
        '.assert ^a_bin = ES_R_A_BANK, error, "drift"\n'
        '    .incbin "a.bin"\n')
    assert _credits(src, "ES_R_A")


# --------------------------------------------------------------------------
# the wiring
# --------------------------------------------------------------------------

# The two gate-LIST rows use a regex rather than a literal, because the list
# legitimately grows: `time-check` joined it on 2026-08-06 and turned both
# literals into false reds that said "rom-unbacked is missing" about a line
# that contained rom-unbacked. What is being asserted is MEMBERSHIP of the
# list, not its exact spelling — a test that breaks whenever a sibling gate
# is added trains people to edit the test instead of reading it.
@pytest.mark.parametrize("path,needle,what", [
    ("Makefile", re.compile(r"^push:(?:\s+[\w-]+)*\s+rom-unbacked\b", re.M),
     "`make push`'s prerequisites — the documented front door"),
    ("tools/git-hooks/pre-push",
     re.compile(r"^for gate in(?:\s+[\w-]+)*\s+rom-unbacked\b", re.M),
     "the pre-push hook's gate loop"),
    # There was a fourth row here — the hosted workflow's own step. The
    # workflow was retired on 2026-08-22 and the row went with the file it
    # read. The surface it stood for is now `make gates` (and `make
    # bare-check`, which runs the gate block inside its clone), which reaches
    # `rom-unbacked` through the `gates:` list rather than a restated step.
    ("tools/setup.sh", "make rom-unbacked",
     "tools/setup.sh's bring-up proof on a fresh clone"),
])
def test_rom_unbacked_is_wired_where_toy_bad_is(path, needle, what):
    """docs/37 §4 and AGENTS.md both present this gate as toy-bad's
    presence-side twin. It landed wired into `make gates` and into `make test`
    only — so the surfaces a human and a fresh clone actually go through did
    not run it. A doc calling two gates twins while one of them
    runs in half the places is the shape this test exists to stop.

    Textual on purpose: running `make push` would push, and running the hook
    would need a remote. What is being checked is the WIRING, and the wiring
    is text in these three files.
    """
    text = (SUPERFORGE / path).read_text()
    assert "toy-bad" in text, f"{path}: toy-bad's own wiring moved — update this test"
    hit = needle.search(text) if hasattr(needle, "search") else (needle in text)
    assert hit, f"rom-unbacked is missing from {what} ({path})"


# --------------------------------------------------------------------------
# the hatch must CITE, not narrate
# --------------------------------------------------------------------------

_N = iter(range(1000))


def _feature(tmp_path, backed_by: str):
    """A one-claim feature dir. The dir NAME is the feature name — schemas.py
    checks that before it looks at any claim."""
    d = tmp_path / f"hatch{next(_N)}"
    d.mkdir()
    p = d / "feature.toml"
    p.write_text(f'name = "{d.name}"\nrole = "blob"\n\n'
                 '[[claims.rom]]\nname = "y"\nbytes = 16\n'
                 f'backed_by = {backed_by!r}\n')
    return p


def test_backed_by_prose_with_no_repo_path_is_refused(tmp_path):
    """The one-line re-opening of the grad_tabs bug, closed.

    Non-emptiness was the whole bar. A developer facing the red gate could
    write `backed_by = "the asset tool generates it"` and go green with the
    claim still unbacked — a plausible sentence, no data, no way to check it.

    The `; WIDTH-LINT: ok — <reason>` precedent this was modelled on is weaker
    than it looks here on two axes: that override suppresses ONE finding at ONE
    site, and it sits in the .asm line a reviewer is already reading. This one
    suppresses a claim's whole presence check — every chunk of a bank_tiled
    claim — from a feature.toml an ASM change's reviewer never opens.
    """
    sub = schemas.load_substrate(ALLOC / "substrate.toml")
    for prose in ("the asset tool generates it",
                  "trust me, it's in the ROM",
                  "generated at build time by the audio pipeline"):
        with pytest.raises(schemas.SchemaError) as e:
            schemas.load_feature(_feature(tmp_path, prose), sub)
        assert "names no file that exists" in str(e.value)
        assert "backed_by" in str(e.value)


def test_backed_by_citing_a_real_path_is_accepted(tmp_path):
    """...and the check is a citation check, not a vocabulary check: the same
    sentence passes the moment it names something a reader can open."""
    sub = schemas.load_substrate(ALLOC / "substrate.toml")
    ok = ('assets/audio/export/tad_audio_data.asm:119 -> segment AUDIO_DATA0, '
          'mapped by vendor/rom/lorom_512k.cfg')
    f = schemas.load_feature(_feature(tmp_path, ok), sub)
    assert f.rom[0].backed_by.startswith("assets/audio/export")


def test_a_path_outside_the_repo_does_not_satisfy_the_citation(tmp_path):
    """`../` in a `backed_by` is a stale citation, never a build dependency.
    A hatch pointing out of the tree is prose with a slash in it."""
    sub = schemas.load_substrate(ALLOC / "substrate.toml")
    with pytest.raises(schemas.SchemaError):
        schemas.load_feature(
            _feature(tmp_path, "../some-other-repo/engine/tad_bridge.asm"), sub)


def test_every_live_backed_by_in_the_tree_cites_something_real():
    """The in-tree guard for the hatch itself. Reads every feature.toml the
    allocator can see and requires each declared `backed_by` to resolve — so a
    new exemption cannot land as prose, and the two that exist stay honest."""
    import tomllib
    seen = 0
    for toml in sorted((SUPERFORGE / "engine" / "features").glob("*/feature.toml")):
        d = tomllib.loads(toml.read_text())
        for c in d.get("claims", {}).get("rom", []):
            if "backed_by" in c:
                seen += 1
                assert schemas._cites_a_repo_path(c["backed_by"]), (
                    f"{toml}: `backed_by` for '{c.get('name')}' cites no path "
                    f"that exists in this repo")
    assert seen >= 1, "no live backed_by found — has the hatch moved?"


# --------------------------------------------------------------------------
# the teeth, against weakenings SHORT OF REMOVAL
# --------------------------------------------------------------------------
#
# `test_target_goes_RED_when_the_rule_is_removed` catches DELETION.
# `test_declaration_block_is_narrow_enough_to_be_teeth` catches every
# line-radius weakening of >= 6 lines. A later review measured two mutations that
# passed all 13 tests: a +-3-line radius, and substring matching of literal
# references. Both are weakenings a plausible implementer reaches for — +-3 is
# exactly the radius `; WIDTH-LINT: ok` and `; CHANNEL-LINT: ok` use — and both
# are blind on the tree's own spacing. These two tests are what makes them red.

def test_the_rule_holds_at_the_REAL_trees_claim_site_spacing():
    """The fixture spaces claim sites ~6 lines apart;
    `game/breaker/main.asm` spaces them **4**. So the narrowness test passed
    while a +-3-line window — blind on breaker — passed with it.

    Runs the rule over the SHIPPING file with exactly one `.incbin` removed
    (the variant ca65 accepts: the label and both `.assert`s stay, so the drift
    asserts still pass). `ES_R_FONT_BIN`'s neighbour sits 4 lines below it, and
    must not credit it.
    """
    real = SUPERFORGE / "game" / "breaker" / "main.asm"
    src = real.read_text().splitlines()
    victim = '.incbin "font_2bpp.bin"'
    assert sum(victim in l for l in src) == 1, (
        "breaker's font_bin claim site moved — update this test's victim")
    planted = [l for l in src if victim not in l]

    ms, _ = no_literals._rom_backing_refs(planted)
    def credited(sym):
        return any(m(sym) or any(m(sym + s) for s in no_literals.ROM_SYM_SUFFIXES)
                   for m in ms)

    assert not credited("ES_R_FONT_BIN"), (
        "a neighbouring blob's .asserts credited ES_R_FONT_BIN with its own "
        ".incbin deleted — the declaration block is wider than the 4-line "
        "spacing the shipping tree actually uses")
    # ...and the neighbour, whose claim site is intact, IS still credited — so
    # this cannot pass by the rule having stopped crediting anything.
    assert credited("ES_R_BRK_BG_CHR_ROM")


def test_a_literal_reference_matches_EXACTLY_not_as_a_substring():
    """The templated case had a negative assertion; the literal
    case had none, so turning exact matching into substring matching passed all
    13 tests. A prefix-similar claim in the same composition would then be
    credited by a neighbour it has nothing to do with — silently, since the
    census would still read `N via an .incbin claim site`.
    """
    src = ('.segment "BANK1"\n'
           'abc_bin:\n'
           '    .incbin "abc.bin"\n'
           '.assert ^abc_bin = ES_R_ABC_BANK, error, "drift"\n')
    ms, _ = no_literals._rom_backing_refs(src.splitlines())
    def credited(sym):
        return any(m(sym) or any(m(sym + s) for s in no_literals.ROM_SYM_SUFFIXES)
                   for m in ms)

    assert credited("ES_R_ABC"), "the claim's own site stopped crediting it"
    for other in ("ES_R_AB", "ES_R_A", "ES_R_ABCD", "ES_R_ABC_EXTRA"):
        assert not credited(other), (
            f"{other} was credited by ES_R_ABC's claim site — literal "
            f"references are matching loosely")


# --------------------------------------------------------------------------
# KNOWN LIMIT 1, closed: the chunk count is DERIVED
# --------------------------------------------------------------------------
#
# The limit used to say a short `.repeat` was caught by "the linker's segment
# sizes and the per-chunk `.assert`". A later review measured it: `.repeat 8` ->
# `.repeat 7` on microzero's world map left the backing gate, ca65 AND ld65 all
# green, the ROM the same 524,288 bytes, and 18,478 bytes of world map replaced
# by $FF fill. A stated-and-wrong backstop is worse than a stated hole — it
# retires the question. The close is to stop narrating the count: the allocator
# emits ES_R_<NAME>_CHUNKS and a hand-written count is a build refusal.

def test_allocator_emits_a_chunk_count_per_bank_tiled_claim(tmp_path):
    """The derived count exists, and equals the placements actually packed."""
    out = tmp_path / "m"
    r = subprocess.run(
        [sys.executable, str(ALLOC / "allocate.py"), "--game", "game/microzero",
         "--features-dir", "engine/features", "--out", str(out)],
        cwd=SUPERFORGE, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    inc = (out / "engine_state_globals.inc").read_text()
    d = json.loads((out / "symbol_map.json").read_text())
    packed = {}
    for p in d["globals"]:
        if p["class"] == "rom" and p["sym"].rsplit("_T", 1)[-1].isdigit():
            packed[p["sym"].rsplit("_T", 1)[0]] = \
                packed.get(p["sym"].rsplit("_T", 1)[0], 0) + 1
    assert packed, "microzero has no bank_tiled claim — this test's subject moved"
    for base, n in packed.items():
        assert f"{base}_CHUNKS = {n}" in inc, (
            f"{base}_CHUNKS missing or wrong: the .repeat count would have to "
            f"be narrated in ASM again")


def test_a_NARRATED_chunk_count_is_refused(tmp_path):
    """THE reproduction, run as a test: `.repeat 8` -> `.repeat 7`.

    Before this change that produced a green gate, a green ca65, a green ld65,
    a 524,288-byte ROM and 18,478 bytes of $FF where the world map should be.
    Now the hand-written count is the refusal, so the short-count residue
    cannot be written at all.
    """
    src = (SUPERFORGE / "game" / "microzero" / "main.asm").read_text()
    anchor = ".repeat ES_R_WORLD_MAP_CHUNKS, WI"
    assert anchor in src, "microzero's world-map claim site moved"
    planted = tmp_path / "main_short_repeat.asm"
    planted.write_text(src.replace(anchor, ".repeat 7, WI"))
    r = gate(SUPERFORGE / "build" / "mz" / "symbol_map.json",
             "--partial-files", planted)
    assert r.returncode == 1, (
        "a hand-written `.repeat 7` around a templated claim site was "
        f"ACCEPTED — KNOWN LIMIT 1 is still open:\n{r.stdout}{r.stderr}")
    assert "NARRATED CHUNK COUNT" in r.stderr
    assert "ES_R_WORLD_MAP_CHUNKS" in r.stderr, (
        "the refusal must name the emitted symbol to use instead")
    # --partial-files must NOT silence it: unlike the backing question, "is
    # this count narrated" is answerable from a single file
    assert "rom backing: SKIPPED" in r.stdout or r.returncode == 1


def test_the_derived_count_is_not_skipped_by_partial_files(tmp_path):
    """The opt-out is scoped to the whole-composition question only."""
    planted = tmp_path / "n.asm"
    planted.write_text(
        '.segment "BANK1"\n'
        '.repeat 4, TI\n'
        '.ident(.sprintf("t%d", TI)):\n'
        '    .incbin "t.bin", TI * 32768, 32768\n'
        '.assert ^.ident(.sprintf("t%d", TI)) = '
        '.ident(.sprintf("ES_R_FIXTURE_TILES_T%d_BANK", TI)), error, "drift"\n'
        '.endrepeat\n')
    for extra in ([], ["--partial-files"]):
        r = gate(SUPERFORGE / "build" / "mz" / "symbol_map.json", *extra, planted)
        assert r.returncode == 1 and "NARRATED CHUNK COUNT" in r.stderr, (
            f"narration went unreported with {extra}:\n{r.stdout}{r.stderr}")


def test_no_shipping_asm_narrates_a_chunk_count():
    """The in-tree guard. Every claim site takes the emitted count.

    This used to say "and mode7_stream's per-chunk MVN stub table, the same
    narration one step downstream". That stub table no longer names chunk
    symbols by template: the blob-binding retrofit (an earlier phase a later sweep) made
    mode7_stream blob-agnostic, and the name cannot enter a feature file
    because `scan_blanket_rom_template` refuses any `ES_R_...%s` form. The
    table now reads `.repeat M7S_CHUNKS` / `.byte $54, $7E, M7S_BLOB_BANK +
    CI`, with the count still DERIVED — the includer binds
    `M7S_CHUNKS = ::ES_R_WORLD_MAP_CHUNKS`.

    STATED LIMIT that trade opened: an includer that binds a NARRATED
    `M7S_CHUNKS = 8` is not visible to `scan_chunk_count_narration`, which
    looks for a `.repeat <literal>` with a templated body in ONE file. The
    binding and the `.repeat` are now in different files by construction.
    """
    import re as _re
    roots = [SUPERFORGE / "game", SUPERFORGE / "engine", SUPERFORGE / "vendor" / "probes",
             SUPERFORGE / "tests" / "fixtures" / "rom_backing"]
    checked = 0
    for root in roots:
        for f in sorted(root.rglob("*.asm")):
            fs = no_literals.scan_chunk_count_narration(
                f, f.read_text().splitlines())
            checked += 1
            assert not fs, "\n".join(str(x) for x in fs)
    assert checked > 20, f"only {checked} .asm scanned — the roots moved"
    # ...and the guard is armed: the tree HAS templated chunk sites to narrate.
    # Three files, and they are the three that SHOULD have them — the two real
    # claim sites beside their `.incbin` (microzero's main.asm, the vendored
    # col_map probe) plus the backed fixture. It was four until mode7_stream
    # stopped naming a blob (see the docstring); the bound was lowered with
    # that removal rather than left to be met by an unrelated file.
    hits = sorted(str(f.relative_to(SUPERFORGE))
                  for root in roots for f in root.rglob("*.asm")
                  if _re.search(r'ES_R_[A-Z_]*_T%d', f.read_text()))
    assert len(hits) >= 3, f"only {hits} templated chunk site(s) — guard disarmed"


# --------------------------------------------------------------------------
# scanned is not assembled
# --------------------------------------------------------------------------
#
# THE SEMANTICS CHOSEN. A claim site credits a claim only if it lives in a file
# ca65 actually assembles into THIS composition — the `.include` closure of the
# translation unit's root. The root is the first positional file (`--asm-root`
# overrides); the closure is resolved by BASENAME against the scanned list,
# because `.include "scene_mgr.asm"` is resolved by ca65 against a `-I` set
# this tool never receives.
#
# Why that shape: the gate's promise is "something includes these bytes into
# THIS rom". What it checked was "some .asm somewhere in the argument list
# mentions the symbol", and the argument list comes from a Makefile wildcard
# over ALL of engine/features. For microzero the two differ by 9 files.
#
# Error direction: a wrong root collapses the closure and every claim reads
# UNBACKED — a loud refusal, never a silent pass.

def test_a_claim_site_in_an_UNASSEMBLED_file_does_not_credit(tmp_path):
    """The unassembled-file arm, end to end.

    Delete microzero's grad_tabs claim site (arm A: refused), then add the
    identical four lines in a file the composition never `.include`s. Before
    this change that arm went GREEN — a claim credited by a file contributing
    no bytes, reachable through the Makefile's own wildcard over
    engine/features.
    """
    mz = SUPERFORGE / "game" / "microzero"
    race = (mz / "scenes" / "race.asm").read_text().splitlines()
    lo = next(i for i, l in enumerate(race) if "gradient_tabs.bin" in l)
    site = race[lo - 1:lo + 3]                       # label, .incbin, asserts
    assert any("ES_R_GRAD_TABS" in l for l in site), site
    stripped = tmp_path / "race.asm"
    stripped.write_text("\n".join(race[:lo - 1] + race[lo + 3:]) + "\n")

    others = ([mz / "main.asm"]
              + [p for p in sorted((mz / "scenes").glob("*.asm"))
                 if p.name != "race.asm"]
              + sorted((SUPERFORGE / "engine" / "features").glob("*/*.asm")))
    mp = SUPERFORGE / "build" / "mz" / "symbol_map.json"

    a = gate(mp, mz / "main.asm", stripped, *others[1:])
    assert a.returncode == 1 and "ES_R_GRAD_TABS'" in a.stderr, (
        f"arm A did not reproduce the bug:\n{a.stdout}{a.stderr}")

    # arm B: the same four lines, in a file nothing .includes
    orphan = tmp_path / "never_included.asm"
    orphan.write_text("\n".join(site) + "\n")
    b = gate(mp, mz / "main.asm", stripped, *others[1:], orphan)
    assert b.returncode == 1 and "ES_R_GRAD_TABS'" in b.stderr, (
        "a claim site in a file the composition never .includes CREDITED the "
        f"claim — scanned is still being read as assembled:\n{b.stdout}{b.stderr}")


def test_the_closure_reach_is_REPORTED_not_just_applied():
    """gen_register.py's discipline: state the limit AND print how far the
    check got. `19/28` is the gap as a number on the summary line rather
    than a sentence in a doc nobody re-reads."""
    mz = SUPERFORGE / "game" / "microzero"
    files = ([mz / "main.asm"] + sorted((mz / "scenes").glob("*.asm"))
             + sorted((SUPERFORGE / "engine" / "features").glob("*/*.asm")))
    r = gate(SUPERFORGE / "build" / "mz" / "symbol_map.json", *files)
    assert r.returncode == 0, r.stderr
    m = re.search(r"credited from (\d+)/(\d+) scanned file\(s\)", r.stdout)
    assert m, f"no reach number on the summary line:\n{r.stdout}"
    inside, scanned = int(m.group(1)), int(m.group(2))
    assert scanned == len(files)
    assert inside < scanned, (
        "the closure reached every scanned file — either the wildcard shrank "
        "or the closure is not being computed")


def test_the_closure_is_computed_over_include_names():
    """The unit. `.include "scenes/race.asm"` reaches race.asm; a file nothing
    names is out; and the walk is transitive (race.asm's own includes are in).
    """
    mz = SUPERFORGE / "game" / "microzero"
    feats = sorted((SUPERFORGE / "engine" / "features").glob("*/*.asm"))
    files = [mz / "main.asm"] + sorted((mz / "scenes").glob("*.asm")) + feats
    inside = no_literals.include_closure(mz / "main.asm", files)

    assert mz / "scenes" / "race.asm" in inside          # named by main.asm
    assert any(p.name == "scene_mgr.asm" for p in inside)  # named by main.asm
    assert any(p.name == "col_map.asm" for p in inside), \
        "transitive: col_map is named by race.asm, not by main.asm"
    for never in ("room_hero.asm", "breaker_bg.asm", "window_iris.asm",
                  "save.asm", "input2.asm"):
        assert not any(p.name == never for p in inside), (
            f"{never} is not in microzero's translation unit but the closure "
            f"admitted it")


def test_a_root_outside_the_scanned_list_is_refused(tmp_path):
    """Fail loud rather than fall back to crediting everything."""
    r = gate(SUPERFORGE / "build" / "mz" / "symbol_map.json",
             "--asm-root", str(tmp_path / "nope.asm"),
             SUPERFORGE / "game" / "microzero" / "main.asm")
    assert r.returncode == 2
    assert "not in the scanned file list" in r.stderr


# --------------------------------------------------------------------------
# KNOWN LIMITs 4 and 5
# --------------------------------------------------------------------------

def test_a_percent_s_template_is_REFUSED_not_expanded(tmp_path):
    """`%d` is a chunk INDEX (`\\d+`); `%s` is a name fragment
    (`\\w+`), so `.sprintf("ES_R_%s_BANK", NAME)` compiles to `^ES_R_\\w+_BANK$`
    and credits EVERY rom claim in the composition — with the census still
    reading `N via an .incbin claim site`, indistinguishable from clean.

    Latent when the auditor found it (all 8 templates in the tree are `%d`).
    A latent blanket exemption is still a blanket exemption.
    """
    planted = tmp_path / "blanket.asm"
    planted.write_text(
        '.segment "BANK1"\n'
        'b_bin:\n'
        '    .incbin "b.bin"\n'
        '.assert ^b_bin = .ident(.sprintf("ES_R_%s_BANK", NAME)), error, "x"\n')
    r = gate(SUPERFORGE / "build" / "mz" / "symbol_map.json", "--partial-files", planted)
    assert r.returncode == 1, (
        f"a %s template was accepted:\n{r.stdout}{r.stderr}")
    assert "BLANKET ROM TEMPLATE" in r.stderr

    # and the measurement behind the finding: it really would credit everything
    ms, _ = no_literals._rom_backing_refs(planted.read_text().splitlines())
    assert any(m("ES_R_TOTALLY_UNRELATED_BANK") for m in ms), (
        "the blast radius this test asserts on has changed — re-derive it")


def test_no_shipping_asm_uses_a_blanket_template():
    """In-tree guard, with an arming check: the tree still HAS templates."""
    roots = [SUPERFORGE / "game", SUPERFORGE / "engine", SUPERFORGE / "vendor" / "probes",
             SUPERFORGE / "tests" / "fixtures" / "rom_backing"]
    templates = 0
    for root in roots:
        for f in sorted(root.rglob("*.asm")):
            lines = f.read_text().splitlines()
            fs = no_literals.scan_blanket_rom_template(f, lines)
            assert not fs, "\n".join(str(x) for x in fs)
            templates += sum(1 for l in lines if 'sprintf("ES_R_' in l)
    assert templates >= 6, f"only {templates} template(s) — guard disarmed"


def test_a_claim_site_inside_an_unevaluated_conditional_does_not_credit(tmp_path):
    """KNOWN LIMIT 4, closed in the safe direction.

    `.if 0` around only the `.incbin`, asserts left outside, is precisely the
    shape docs/37 §1 calls the nasty one: ca65 accepts it and the drift
    asserts still pass. The scan cannot evaluate ca65 conditionals, so a claim
    site inside one no longer credits — the claim reads UNBACKED, which is
    loud and fixable, instead of credited-but-empty, which is the bug.
    """
    src = ('.segment "BANK1"\n'
           'a_bin:\n'
           '.if 0\n'
           '    .incbin "a.bin"\n'
           '.endif\n'
           '.assert ^a_bin = ES_R_A_BANK, error, "drift"\n')
    ms, skipped = no_literals._rom_backing_refs(src.splitlines())
    assert skipped == 1, "the conditional .incbin was not counted"
    assert not any(m("ES_R_A") or m("ES_R_A_BANK") for m in ms), (
        "a claim site inside `.if 0` credited its claim — ca65 emits nothing "
        "there")
    # ...and outside the conditional the same site DOES credit, so this is not
    # passing by the rule having stopped crediting anything
    ms2, skipped2 = no_literals._rom_backing_refs(
        src.replace(".if 0\n", "").replace(".endif\n", "").splitlines())
    assert skipped2 == 0 and any(m("ES_R_A_BANK") for m in ms2)


def _mz_gate(planted_main: Path | None, tmp_path: Path):
    """Run the gate over microzero's real file list, optionally substituting a
    planted copy of `main.asm` as the translation-unit root."""
    mz = SUPERFORGE / "game" / "microzero"
    root = planted_main if planted_main is not None else (mz / "main.asm")
    files = ([root] + sorted((mz / "scenes").glob("*.asm"))
             + sorted((SUPERFORGE / "engine" / "features").glob("*/*.asm")))
    return gate(SUPERFORGE / "build" / "mz" / "symbol_map.json", *files)


def test_a_conditional_claim_site_is_REFUSED(tmp_path):
    """The teeth of KNOWN LIMIT 4 at whole-gate level: wrap microzero's only
    `font_bin` claim site in a never-taken `.ifdef` and the claim must read
    UNBACKED rather than credited-but-empty."""
    mz = SUPERFORGE / "game" / "microzero"
    planted = tmp_path / "main.asm"
    planted.write_text((mz / "main.asm").read_text().replace(
        'font_bin:\n    .incbin "font_2bpp.bin"',
        'font_bin:\n.ifdef NEVER_DEFINED\n    .incbin "font_2bpp.bin"\n.endif'))
    r = _mz_gate(planted, tmp_path)
    assert r.returncode == 1 and "ES_R_FONT_BIN'" in r.stderr, (
        f"the conditional claim site still credited:\n{r.stdout}{r.stderr}")


def test_the_conditional_residue_is_reported_in_the_census(tmp_path):
    """gen_register.py's discipline again: a limit that is applied but not
    counted is a limit nobody can see.

    Learned the hard way. An earlier version of this test planted the SAME
    conditional the test above plants — which makes the run RED, and
    `summarise()` is only ever printed on the GREEN path (`no_literals.main`
    returns 1 before reaching it). So the census line the test is named for
    did not exist in the output it read, the assertion fell back to the
    refusal its sibling already covers, and deleting the census suffix from
    `summarise()` left the whole suite green. The name was a contract the
    assertion did not meet — this repo's own rule 2, one level up, in the
    tool that enforces it.

    The plant therefore has to keep the run GREEN: append a never-taken
    claim site for a claim that is ALREADY credited by its real one. The
    residue is then a number on a line that actually gets printed.
    """
    mz = SUPERFORGE / "game" / "microzero"

    # CONTROL first: the unmodified tree prints the census with NO residue
    # suffix, so the assertion below cannot pass by the suffix being
    # unconditional.
    clean = _mz_gate(None, tmp_path)
    assert clean.returncode == 0, f"microzero is not green:\n{clean.stderr}"
    assert "rom backing:" in clean.stdout, (
        f"no census line at all:\n{clean.stdout}")
    assert "did NOT credit" not in clean.stdout, (
        f"the residue suffix printed with nothing to report:\n{clean.stdout}")

    planted = tmp_path / "main.asm"
    planted.write_text((mz / "main.asm").read_text() + (
        '\n; --- planted by test_the_conditional_residue_is_reported_in_the'
        '_census ---\n'
        '; A never-taken second claim site for a claim its REAL site already\n'
        '; credits, so the composition stays backed and the summary prints.\n'
        '.ifdef NEVER_DEFINED\n'
        'font_bin_debug_copy:\n'
        '    .incbin "font_2bpp.bin"\n'
        '.assert ^font_bin_debug_copy = ES_R_FONT_BIN_BANK, error, "planted"\n'
        '.endif\n'))
    r = _mz_gate(planted, tmp_path)

    assert r.returncode == 0, (
        "the planted site is a DUPLICATE of one that already credits, so the "
        f"gate must stay green:\n{r.stdout}{r.stderr}")
    assert "1 .incbin(s) inside an unevaluated .if/.ifdef did NOT credit" \
        in r.stdout, (
        "the census does not report the conditional residue — KNOWN LIMIT 4 "
        f"is applied but not counted:\n{r.stdout}")
    assert "KNOWN LIMIT 4" in r.stdout, (
        f"the residue is counted but not attributed to its limit:\n{r.stdout}")
