"""tools/harness_faults.py, tried against the two REAL faults it was built for.

WHY THIS MODULE EXISTS. `make bare-check` returns one bit, and two very
different events set it: a rail that broke, and the process-global Mesen2
core losing a WALL-clock race under the load the gate itself creates.
Telling them apart cost a forensic dig per run until the tool landed, so
the tool has to be right about the exact shapes it will meet.

Test surface. The fixtures under `tests/fixtures/bare_check_faults/` are
VERBATIM pytest output, not hand-written approximations:

  * `measure_wedge.log` — the FAILURES block from the 2026-08-26 landing
    run at 715dec0. `make measure`'s probe wait hit the 30-second stall
    guard and the surface exception is an AssertionError, so this is the
    case a naive "AssertionError means defect" rule reads backwards.
  * `teardown_close.log` — the ERRORS block from the second run of the
    same tip. `Machine.close()` missed its ten-second resume deadline in
    an autouse fixture's TEARDOWN, after the test itself passed.
  * `plain_defect.log` — the negative control, generated by running two
    genuinely failing tests under this repo's pytest. A real log, not a
    mock, so the tool cannot pass by recognising a fixture's shape.

The drift guard below is the load-bearing one: every message fragment in
LIVENESS_GUARDS must still exist in the vendor source it names. Without
it a reworded guard would leave the table matching nothing, and every
future fault would read `defect` while the tool still looked alive.
"""
import pathlib
import sys

import pytest

SUPERFORGE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SUPERFORGE / "tools"))

import harness_faults as hf                                     # noqa: E402

FIX = SUPERFORGE / "tests" / "fixtures" / "bare_check_faults"


def _scan(name):
    return hf.scan((FIX / name).read_text())


# --- the drift guard -------------------------------------------------------

@pytest.mark.parametrize("src,frag", hf.LIVENESS_GUARDS,
                         ids=lambda v: v.split()[0] if " " in v else v)
def test_every_guard_fragment_is_still_in_the_source_it_names(src, frag):
    """A reworded guard must break this, not silently disarm the tool."""
    text = (SUPERFORGE / src).read_text()
    assert frag in text, (
        f"{src} no longer contains {frag!r}. Either the guard was reworded "
        f"(update LIVENESS_GUARDS to match) or it was removed (drop the row). "
        f"Leaving it stale makes every harness fault read as a defect.")


def test_the_guard_table_is_not_empty():
    """A table emptied by a bad edit would read every fault as a defect."""
    assert len(hf.LIVENESS_GUARDS) >= 3


# --- the two real harness faults ------------------------------------------

def test_the_measure_wedge_reads_as_harness_despite_an_assertion_surface():
    faults = _scan("measure_wedge.log")
    assert len(faults) == 1, faults
    f = faults[0]
    assert f["test"] == "test_measure_multi_queue_arm_cost"
    assert f["file"] == "tests/test_measure_vblank.py"
    assert f["phase"] == "call"
    # Both are named: the wedge is the cause, the assertion is the surface.
    assert f["exceptions"] == ["TimeoutError", "AssertionError"]
    assert f["reading"] == "harness-liveness"


def test_the_teardown_close_is_read_as_a_teardown_not_a_test_failure():
    faults = _scan("teardown_close.log")
    assert len(faults) == 1, faults
    f = faults[0]
    assert f["test"] == "test_the_whole_screen_is_two_sprites_over_bare_backdrop"
    assert f["file"] == "tests/test_sprite_game.py"
    assert f["phase"] == "teardown", "the test PASSED; only its teardown failed"
    assert f["exceptions"] == ["machine.MachineError"]
    assert f["reading"] == "harness-liveness"


# --- the negative control --------------------------------------------------

def test_a_plain_failing_test_reads_as_a_defect():
    faults = _scan("plain_defect.log")
    assert [f["reading"] for f in faults] == ["defect", "defect"], faults
    assert [f["exceptions"][0] for f in faults] == ["AssertionError", "ValueError"]


def test_the_inner_rules_do_not_become_phantom_faults():
    """`_ _ _ _` frame separators share the banner shape; they are not faults."""
    for name in ("measure_wedge.log", "teardown_close.log"):
        assert len(_scan(name)) == 1, name


# --- the aggregate reading -------------------------------------------------

def test_summarize_reads_none_defect_harness_and_mixed():
    assert hf.summarize([]) == "none"
    both = _scan("measure_wedge.log") + _scan("plain_defect.log")
    assert hf.summarize(_scan("measure_wedge.log")) == "harness-liveness"
    assert hf.summarize(_scan("plain_defect.log")) == "defect"
    assert hf.summarize(both) == "mixed"


# --- the two false-positive paths that are closed on purpose ---------------

def test_a_guard_message_in_source_lines_alone_is_not_a_harness_reading():
    """Only `E ` lines carry the RAISED message.

    The wedge fixture displays `_wait_stall_guard`'s body, so its source
    lines hold the fragment too. A rule that matched the whole block would
    read any test that merely PRINTS a guard as a harness fault.
    """
    block = (
        "=================================== FAILURES ==================\n"
        "______________________ test_shows_the_guard_text ______________\n"
        "\n"
        "    def test_shows_the_guard_text():\n"
        "        # the emulated frame counter has not advanced for 30.0s\n"
        ">       assert row == 7\n"
        "E       AssertionError: assert 6 == 7\n"
        "\n"
        "tests/test_thing.py:12: AssertionError\n"
    )
    faults = hf.scan(block)
    assert [f["reading"] for f in faults] == ["defect"], faults


def test_the_guards_own_test_modules_are_never_read_as_harness():
    """test_park_guard.py asserts ON the guard text; a red there is a defect."""
    block = (
        "=================================== FAILURES ==================\n"
        "______________________ test_the_guard_names_the_culprit _______\n"
        "\n"
        ">       assert 'has not advanced' in out\n"
        "E       AssertionError: the emulated frame counter has not advanced "
        "for 30.0s\n"
        "\n"
        "tests/test_park_guard.py:347: AssertionError\n"
    )
    faults = hf.scan(block)
    assert faults[0]["file"] == "tests/test_park_guard.py"
    assert faults[0]["reading"] == "defect", (
        "a module whose job is to prove the guard fires must not be able to "
        "excuse itself with the guard's own message")
