#!/usr/bin/env bash
# Build `mill`'s DIRECT-COLOUR variant: build/mill_direct.sfc.
#
# The tools/build_rs_probe.sh shape — one variant image off the shipping rail's
# own sources, linked by the same helper, named at its own call site so
# `tools/rail_registered.py --expected-images` finds it without a list. It
# needs ONE thing that no other variant in this tree needs, and this is the
# whole reason it is not a bare `-D`:
#
#   IT COMPOSES A DIFFERENT DECLARATION, so it needs its own allocator run.
#
# `direct_color` is a field on `[[claims.video]]` and it composes CGWSEL bit 0
# (docs/99 §4, docs/100 §3). The scene writes CGWSEL from the emitted
# `ES_SCR_<ID>_CGWSEL`, as it already did, so there is no ASM change for the
# register at all — the bit arrives because the DECLARATION changed. A `-D`
# cannot express that, and hand-OR-ing the bit at the write site is the second
# uncheckable copy of a claim that the emitted encodings exist to prevent.
#
# WHY THE VARIANT MANIFEST IS DERIVED AND NOT COMMITTED. It differs from
# `game/mill/game.toml` in one token — `mil_mode` becomes `mil_mode_dc`, the
# same claim with `direct_color = true` — and a committed copy of a manifest
# is a second thing to keep in step with the first. Deriving it makes the
# "one declaration different" claim MECHANICALLY TRUE rather than asserted:
# the substitution below refuses unless it applies exactly once, so the day
# mill's globals change, this build follows or stops. It also keeps the rail
# census honest: `game/*` still holds ONE mill, because this is a variant of
# that rail and not a second one.
#
# WHAT IS SHARED, WHICH IS EVERYTHING ELSE. Same main.asm, same scenes, same
# features, same geometry, same offset table, same BG2 and OBJ art. The two
# ROMs differ in BG1's CHR page, BG1's two tilemaps (whose palette field is
# dead in the indexed build and load-bearing here) and CGWSEL bit 0.
#
# THE PALETTE CLAIM IS STILL MADE AND STILL UPLOADED. `mil_bg`'s 96-word BG1
# palette lands in CGRAM 32..127 in this build too and BG1 does not read a word
# of it — direct colour is all-or-nothing for the layer. Dropping the claim
# would make the two builds differ in their ALLOCATION as well as in their
# picture, and the point of the variant is that they do not.
#
# Run from the repo root, AFTER `make mill` (the shipping assets and the
# shipping map must exist).
set -euo pipefail

BUILD=build
VROM=vendor/rom
SRC=game/mill/main.asm
MAP=$BUILD/mild                 # the VARIANT's emitted map
GAME=$BUILD/mild_game           # ...and the derived manifest it is built from

INC="-I $MAP -I $VROM -I game/mill -I $BUILD/assets
     -I engine/features/scene_mgr -I engine/features/input
     -I engine/features/fade -I engine/features/region
     -I engine/features/tick_scale
     -I engine/features/mil_bg -I engine/features/mil_opt
     -I engine/features/mil_obj -I engine/features/oam_sprites
     -I engine/features/mil_tint
     -I engine/features/mil_band"

if [ ! -f "$BUILD/mil/symbol_map.json" ]; then
    echo "build_mill_direct: run 'make mill' first ($BUILD/mil is missing)" >&2
    exit 1
fi

# ---- 1. BG1's art, re-cut as direct colour --------------------------------
python3 tools/gen_mill_direct.py "$BUILD/assets"

# ---- 2. the derived manifest ----------------------------------------------
mkdir -p "$GAME"
python3 - "$GAME" <<'PY'
import sys
from pathlib import Path

game = Path(sys.argv[1])
src = Path("game/mill/game.toml").read_text()
OLD, NEW = '"mil_mode"', '"mil_mode_dc"'
if src.count(OLD) != 1:
    raise SystemExit(
        f"build_mill_direct: game/mill/game.toml names {OLD} "
        f"{src.count(OLD)} time(s), expected exactly 1 — the variant is a "
        f"ONE-TOKEN substitution and it has stopped being one. Fix the "
        f"manifest or this script, do not loosen the guard.")
head = ("# GENERATED by tools/build_mill_direct.sh from game/mill/game.toml.\n"
        "# One token differs: mil_mode -> mil_mode_dc, the same video claim\n"
        "# with direct_color = true. Everything else is the shipping rail's.\n")
(game / "game.toml").write_text(head + src.replace(OLD, NEW))
# The user state is the rail's, unchanged: same scenes, same scaled rate.
(game / "state.toml").write_text(
    "# GENERATED by tools/build_mill_direct.sh — a copy of "
    "game/mill/state.toml.\n" + Path("game/mill/state.toml").read_text())
PY

# ---- 3. the variant's own allocation --------------------------------------
python3 allocator/allocate.py --game "$GAME" --features-dir engine/features \
    --out "$MAP"

# ---- 4. the same gates the shipping recipe runs ---------------------------
# shellcheck disable=SC2046
python3 allocator/no_literals.py --map "$MAP/symbol_map.json" \
    game/mill/main.asm game/mill/scenes/hall.asm game/mill/scenes/lobby.asm \
    $(ls engine/features/*/*.asm)

# ---- 5. link ---------------------------------------------------------------
build_variant() {
    local name="$1"; shift
    # shellcheck disable=SC2086
    ca65 --cpu 65816 $INC --bin-include-dir "$BUILD/assets" "$@" \
        -o "$BUILD/$name.o" "$SRC"
    ld65 -C "$VROM/lorom_512k.cfg" -o "$BUILD/$name.sfc" "$BUILD/$name.o"
    python3 tools/fix_checksum.py "$BUILD/$name.sfc" >/dev/null
    echo "built $BUILD/$name.sfc"
}

build_variant mill_direct -D MIL_DIRECT=1
