"""Fit mill's BG1 palette to WHAT IS ON SCREEN, and choose the split.

WHY THIS EXISTS. `mil`'s four ramps were built by interpolating swatches read
off the concept sheet, and the kit art was quantised onto them by nearest
entry. That places the entries along a 1-D CURVE while the art is a 3-D CLOUD
around it: measured on the tree that shipped it, only 76 of 96 claimed CGRAM
entries were ever drawn. An 8bpp layer indexes CGRAM directly with no palette
field, which means the palette can be chosen FROM the art rather than the art
fitted onto it -- and that is the difference between 8bpp buying addressing
and 8bpp buying depth.

WHAT IS FITTED. The first cut of this file fitted the SHEETS: every pixel of
every kit asset, sampled at its source resolution, whether or not the rail
ever painted it and however small it was painted. That weights a 778-row rail
strip that became a 32-pixel cross-section the same as the lobby wall that
covers a whole scene. This cut fits the PICTURE instead: it runs the painters
with `gen_mill_assets.SOURCE` set, which makes the two quantisers hand back
source colours in place of entries, and takes every BG1 pixel of the hall's
two screens and the lobby's one, each counted once. A colour's weight is the
area it covers, a sheet the rail never draws weighs nothing, and the delivered
art -- which is most of what is on screen -- is in the cloud, which the sheet
fit never saw.

WHAT IS CHOSEN. The ramp lengths. Ninety-six entries across four families
used to be split by hand (36/16/32/12); here each family's error is measured
at every candidate length and the split that minimises the total on-screen
error is taken, subject to a FLOOR per family: no ramp shorter than eight
steps, and the warm ramp no shorter than the sixteen tones the painters
dither on by hand (`TONES`, recorded by the same run). The painters address
tones as FRACTIONS of a ramp, so a split can move without any of them being
retouched.

Per family, weighted k-means over the on-screen cloud, then sorted by
luminance so the ramp stays MONOTONE and `Wm(t)` keeps meaning "t of the way
from dark to light".

WHY THE OUTPUT IS COMMITTED rather than computed at build time: the argument
KIT_BOX carries. A build must not depend on a clustering pass agreeing with
itself run to run, and running the painters twice would cost every build.
Regenerate deliberately:

    python3 tools/fit_mill_palette.py            # prints the block
    python3 tools/fit_mill_palette.py --write    # ...and splices it into
                                                 #   gen_mill_assets.py

DETERMINISTIC: no randomness anywhere -- the seeding walks the sorted cloud
-- so the same tree gives the same palette, and a second run on the tree it
just wrote changes nothing (the cloud does not depend on the palette).
"""
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
GEN = HERE / "gen_mill_assets.py"
_argv = sys.argv
sys.argv = [sys.argv[0], "/tmp/_fit_scratch"]
sys.path.insert(0, str(HERE))
import gen_mill_assets as G                                  # noqa: E402
sys.argv = _argv

ITERS = 14
WEIGHT = (2, 4, 1)               # the eye's, and map_to_palette's own weighting
TOTAL = 96                       # BG1's claim: CGRAM 32..127
FLOOR = 8                        # no ramp shorter than this
STEP = 4                         # the split is searched on this grid
SCREEN_ROWS = 224
FAMILIES = [("STEEL_COLD", "cold", G.SW_STEEL_COLD, G.IX_COLD, G.N_COLD),
            ("STEEL_WARM", "warm", G.SW_STEEL_WARM, G.IX_WARM, G.N_WARM),
            ("MOLTEN", "molten", G.SW_MOLTEN, G.IX_MOLTEN, G.N_MOLTEN),
            ("BRASS", "brass", G.SW_BRASS, G.IX_BRASS, G.N_BRASS)]
BEGIN = "# --- GENERATED by tools/fit_mill_palette.py: begin ---"
END = "# --- GENERATED by tools/fit_mill_palette.py: end ---"


def _exp(c):
    return tuple((v << 3) | (v >> 2) for v in c)


def _d2(p, q):
    return (WEIGHT[0] * (p[0] - q[0]) ** 2 + WEIGHT[1] * (p[1] - q[1]) ** 2
            + WEIGHT[2] * (p[2] - q[2]) ** 2)


def on_screen():
    """{family: {rgb888: pixels}} for every BG1 pixel the two rooms show, plus
    the per-family area the painters draw by hand and what was rejected."""
    G.SOURCE, G.TONES = {}, {}
    # EVERY ROW A ROOM SHOWS: the hall's camera runs the map's full height,
    # and the lobby is one screen of its own. (This used to add the melt's
    # screen on top, from a MELT_CAM the generator no longer has — the melt
    # became the floor of both rooms, and this file would not have run.)
    pictures = ((G.paint_bg1(), G.WORLD_H),
                (G.paint_lobby(), SCREEN_ROWS))
    anchors = [(f, [_exp(c) for c in G._anchors(sw)]) for _, f, sw, _, _ in FAMILIES]
    ix = {f: (ix0, n) for _, f, _, ix0, n in FAMILIES}

    def family_of_index(v):
        for f, (ix0, n) in ix.items():
            if ix0 <= v < ix0 + n:
                return f
        raise ValueError(v)

    hist, hand = Counter(), Counter()
    for buf, rows in pictures:
        for y in range(rows):
            for v in buf[y]:
                if v >= 256:
                    hist[G.SOURCE[v]] += 1
                elif v:
                    hand[family_of_index(v)] += 1
    cloud = {f: {} for _, f, _, _, _ in FAMILIES}
    rejected = 0
    for c, w in hist.items():
        if G.is_key_hue(*c):
            rejected += w
            continue
        f = min(anchors, key=lambda a: min(_d2(c, q) for q in a[1]))[0]
        cloud[f][c] = w
    tones = {f: len(G.TONES.get(ix0, ())) for _, f, _, ix0, _ in FAMILIES}
    G.SOURCE, G.TONES = None, None
    return cloud, hand, tones, rejected


def kmeans(cloud, k):
    """k weighted centroids.

    SEEDED BY FARTHEST POINT, not by walking the cloud. The first cut walked
    the sorted cloud by cumulative weight, and on a cloud that is mostly one
    delivered wall of twenty flat colours that put thirteen of fifty-two seeds
    inside the same colour, where Lloyd's step left them: a ramp a quarter
    duplicates while the hall's kit art, six hundred colours of it, shared
    what was left. Here the heaviest colour seeds first and each next seed is
    the colour with the largest weight x squared-distance to the seeds so
    far -- k-means++'s choice, made deterministically -- so every seed starts
    somewhere the cloud actually has weight and nobody else covers. Sorted
    input, so the run does not depend on dict order."""
    pts = sorted(cloud.items())
    cent = [list(max(pts, key=lambda pw: pw[1])[0])]
    near = [_d2(p, cent[0]) for p, _ in pts]
    while len(cent) < k:
        i = max(range(len(pts)), key=lambda i: pts[i][1] * near[i])
        if near[i] == 0:                     # the cloud has no more colours
            cent.append(list(cent[-1]))
            continue
        cent.append(list(pts[i][0]))
        near = [min(d, _d2(p, cent[-1])) for d, (p, _) in zip(near, pts)]
    for _ in range(ITERS):
        sums = [[0, 0, 0, 0] for _ in range(k)]
        for p, w in pts:
            i = min(range(k), key=lambda i: _d2(p, cent[i]))
            s = sums[i]
            s[0] += p[0] * w
            s[1] += p[1] * w
            s[2] += p[2] * w
            s[3] += w
        for i in range(k):
            if sums[i][3]:
                cent[i] = [sums[i][t] / sums[i][3] for t in range(3)]
    return cent


def ramp_of(cloud, k):
    """The family's k-entry ramp in BGR555, monotone by luminance. Exactly k:
    the painters address the ramp by fraction and every step must exist, so
    duplicates after rounding are kept -- a family that cannot fill its ramp
    is saying the art has no more steps to give."""
    ramp = [tuple(min(31, max(0, round(v / 8))) for v in c) for c in kmeans(cloud, k)]
    ramp.sort(key=lambda c: 2 * c[0] + 4 * c[1] + c[2])
    return ramp


def error(cloud, ramp):
    """Area-weighted squared error of the cloud against the ramp, total."""
    exp = [_exp(c) for c in ramp]
    return sum(w * min(_d2(p, q) for q in exp) for p, w in cloud.items())


def choose(cloud, floors, log=lambda *_: None):
    """The split: per-family error at every candidate length on the STEP
    grid, then the combination summing to TOTAL with the least total error."""
    names = [f for _, f, _, _, _ in FAMILIES]
    err, ramps = {}, {}
    for f in names:
        lo = floors[f]
        hi = TOTAL - sum(floors[g] for g in names if g != f)
        for n in range(lo, hi + 1):
            if (n - lo) % STEP and n != hi:
                continue
            ramps[f, n] = ramp_of(cloud[f], n)
            err[f, n] = error(cloud[f], ramps[f, n])
            log(f, n, err[f, n])
    best = None
    sizes = {f: sorted(n for g, n in err if g == f) for f in names}
    for a in sizes[names[0]]:
        for b in sizes[names[1]]:
            for c in sizes[names[2]]:
                d = TOTAL - a - b - c
                if (names[3], d) not in err:
                    continue
                e = err[names[0], a] + err[names[1], b] + err[names[2], c] + err[names[3], d]
                if best is None or e < best[0]:
                    best = (e, (a, b, c, d))
    return best[1], {f: ramps[f, n] for f, n in zip(names, best[1])}, err


def main():
    write = "--write" in sys.argv
    cloud, hand, tones, rejected = on_screen()
    area = {f: sum(cloud[f].values()) for f in cloud}
    total = sum(area.values())
    floors = {f: FLOOR for f in cloud}
    floors["warm"] = max(FLOOR, tones["warm"])     # the ramp the painters dither on
    # THE BASELINE IS THE BLOCK THIS RUN REPLACES -- the ramps and split in
    # the file now -- so the numbers say what this run changed. A second run
    # on the tree it just wrote reports 0% everywhere, which is the
    # determinism claim above made visible.
    old = {f: [tuple(c) for c in getattr(G, f"FIT_{fit}")]
           for fit, f, _, _, _ in FAMILIES}
    old_n = {f: n for _, f, _, _, n in FAMILIES}
    old_err = {f: error(cloud[f], old[f]) for f in cloud}
    split, ramps, _ = choose(cloud, floors,
                             log=lambda f, n, e: print(f"  {f:6} {n:3} {e / total:8.1f}",
                                                       file=sys.stderr))
    new_n = dict(zip([f for _, f, _, _, _ in FAMILIES], split))
    new_err = {f: error(cloud[f], ramps[f]) for f in cloud}

    out = [BEGIN,
           "# Do not hand-edit. Fitted to the PICTURE -- every BG1 pixel of the hall's",
           "# two screens, the melt's one and the lobby's, each counted once -- and the split chosen",
           "# to minimise the total on-screen error (floor 8 a ramp; the warm ramp",
           f"# floors at its {tones['warm']} hand-dithered tones). {total} source px in the",
           f"# cloud, {sum(hand.values())} drawn by hand on the ramps, {rejected} rejected as key",
           "# fringe. Error is the eye-weighted squared distance per on-screen source",
           "# pixel, against the ramps and split this run replaced:"]
    for f in cloud:
        out.append(f"#   {f:6} {area[f]:6} px ({100 * area[f] / total:4.1f}%)  "
                   f"{old_n[f]:2} -> {new_n[f]:2} entries ({len(set(ramps[f]))} distinct)  error "
                   f"{old_err[f] / total:6.1f} -> {new_err[f] / total:6.1f}  "
                   f"(hand-drawn area {hand[f]} px, {tones[f]} tones)")
    te0, te1 = sum(old_err.values()) / total, sum(new_err.values()) / total
    out.append(f"#   total                          error {te0:6.1f} -> {te1:6.1f} "
               f"({100 * (te1 - te0) / te0:+.0f}%)")
    out.append("N_COLD, N_WARM, N_MOLTEN, N_BRASS = " + ", ".join(str(n) for n in split))
    for fit, f, _, _, _ in FAMILIES:
        body = ", ".join(f"({c[0]},{c[1]},{c[2]})" for c in ramps[f])
        out.append(f"FIT_{fit} = [{body}]")
    out.append(END)
    block = "\n".join(out)
    print(block)
    if write:
        src = GEN.read_text()
        a, b = src.index(BEGIN), src.index(END) + len(END)
        GEN.write_text(src[:a] + block + src[b:])
        print(f"wrote {GEN}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
