#!/usr/bin/env python3
"""Generate the OBJ sprite-font HUD glyph CHR (.inc) — milestone 1.

Reuses the kit's built-in font shapes (sf_font_2bpp in lib/macros/sf_text_data.inc):
extracts each glyph's 1-bit 8x8 bitmap (plane0 of the 2bpp data) and re-encodes
it as a 4bpp OBJ tile with the glyph pixels = colour index 1 (so OBJ palette 7
slot 1 is the glyph colour). Adds the HUD markers the ASCII font lacks: filled
bar block, up arrow, down arrow. Output is a static .inc committed to the kit so
the macro layer has no build-time codegen dependency.

Glyph set (HUD readout needs): 0-9, A-Z, space, : . - + and markers up/down/bar.
Tile layout (contiguous OBJ tiles, indices RELATIVE to the OBSEL name base):
  tile 0          : space (blank)  -- also the transparent/blank glyph
  tiles 1..10     : '0'..'9'
  tiles 11..36    : 'A'..'Z'
  tile 37         : ':'
  tile 38         : '.'
  tile 39         : '-'
  tile 40         : '+'
  tile 41         : up arrow    (UPCHR)
  tile 42         : down arrow  (DNCHR)
  tile 43         : full block  (BARCHR, value bar)
The macro maps a source byte to its tile via SF_OBJG_<char> equates emitted here.
"""
import re
import sys
from pathlib import Path

# Resolve the kit's built-in font relative to this tool: tools/gen_obj_font.py ->
# ../lib/macros/sf_text_data.inc. Works from the staging tree or a materialized
# kit (both keep the tools/ + lib/macros/ layout).
SRC = Path(__file__).resolve().parent.parent / "lib" / "macros" / "sf_text_data.inc"

# Parse sf_font_2bpp: char $NN -> list of 8 plane0 bytes (one per row).
def parse_kit_font():
    text = SRC.read_text().splitlines()
    glyphs = {}            # codepoint -> [8 row bytes]
    cur = None
    rows = []
    in_font = False
    for line in text:
        if "sf_font_2bpp:" in line:
            in_font = True
            continue
        if not in_font:
            continue
        if ".endif" in line:
            break
        m = re.match(r"\s*;\s*\$([0-9A-Fa-f]{2})\b", line)
        if m:
            if cur is not None:
                glyphs[cur] = rows
            cur = int(m.group(1), 16)
            rows = []
            continue
        b = re.findall(r"\$([0-9A-Fa-f]{2})", line)
        if b and cur is not None:
            vals = [int(x, 16) for x in b]
            # rows come as pairs (plane0, plane1) identical; take plane0 (even idx)
            for i in range(0, len(vals), 2):
                rows.append(vals[i])
    if cur is not None and cur not in glyphs:
        glyphs[cur] = rows
    return glyphs

# A 1-bit 8x8 bitmap (8 row bytes, bit7=leftmost pixel) -> 4bpp tile bytes (32).
# 4bpp SNES planar: rows 0-7 of plane0/plane1 interleaved (16 bytes), then rows
# 0-7 of plane2/plane3 (16 bytes). Glyph pixels = colour index 1 -> only plane0
# carries bits; planes 1,2,3 = 0.
def bitmap_to_4bpp(rowbytes):
    rb = list(rowbytes[:8]) + [0] * (8 - len(rowbytes))
    out = []
    for r in range(8):
        out.append(rb[r])   # plane0 = the shape
        out.append(0x00)    # plane1 = 0
    out += [0x00] * 16      # planes 2 & 3 = 0
    return out

# Hand-drawn markers (1-bit 8x8 rows, bit7 = leftmost).
def b(s):  # "....##.." -> byte, '#'/'X' = set
    v = 0
    for i, c in enumerate(s[:8]):
        if c in "#X1":
            v |= (0x80 >> i)
    return v

UP_ARROW = [b(s) for s in [
    "...##...",
    "...##...",
    "..####..",
    "..####..",
    ".######.",
    ".######.",
    "########",
    "########",
]]
DOWN_ARROW = [b(s) for s in [
    "########",
    "########",
    ".######.",
    ".######.",
    "..####..",
    "..####..",
    "...##...",
    "...##...",
]]
FULL_BLOCK = [0xFF] * 8

# Build the ordered glyph table.
ORDER = []                                   # (name, codepoint-or-None, rowbytes-or-None)
ORDER.append(("SPACE", 0x20, None))          # tile 0 (from kit font space)
for d in "0123456789":
    ORDER.append((d, ord(d), None))
for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    ORDER.append((c, ord(c), None))
ORDER.append(("COLON", ord(":"), None))
ORDER.append(("DOT",   ord("."), None))
ORDER.append(("DASH",  ord("-"), None))
ORDER.append(("PLUS",  ord("+"), None))
ORDER.append(("UP",   None, UP_ARROW))
ORDER.append(("DOWN", None, DOWN_ARROW))
ORDER.append(("BAR",  None, FULL_BLOCK))

def main():
    kit = parse_kit_font()
    lines = []
    lines.append("; =============================================================================")
    lines.append("; sf_obj_text_data.inc — OBJ sprite-font HUD glyph CHR (4bpp) + tile map")
    lines.append("; =============================================================================")
    lines.append("; GENERATED by tools/gen_obj_font.py — DO NOT EDIT BY HAND.")
    lines.append("; The kit's built-in font shapes (sf_font_2bpp, lib/macros/sf_text_data.inc)")
    lines.append("; re-encoded as 4bpp OBJ tiles, glyph pixels = colour index 1 (OBJ palette 7")
    lines.append("; slot 1). Plus the HUD markers the ASCII font lacks: up/down arrows + a full")
    lines.append("; block for value bars. 8x8, 32 bytes/tile, tiles contiguous from base.")
    lines.append(";")
    lines.append("; Tile indices are RELATIVE to the OBSEL OBJ name base (the HUD uploads this")
    lines.append("; blob at a caller-chosen base tile, default 1024 = VRAM word $4000 / OBSEL=$62).")
    lines.append("; The sf_obj_print/sf_obj_num macros map a character to SF_OBJG_<glyph> below.")
    lines.append("; =============================================================================")
    lines.append("")
    lines.append(".ifndef SF_OBJ_TEXT_DATA_INC")
    lines.append("SF_OBJ_TEXT_DATA_INC = 1")
    lines.append("")
    lines.append("; --- glyph tile indices (relative to the upload base tile) ---")
    for i, (name, cp, _) in enumerate(ORDER):
        lines.append(f"SF_OBJG_{name:<6} = {i}")
    lines.append(f"SF_OBJ_FONT_TILES = {len(ORDER)}                ; glyph count")
    lines.append(f"SF_OBJ_FONT_BYTES = {len(ORDER)*32}              ; blob size (tiles * 32)")
    lines.append("")
    lines.append("; --- the 4bpp CHR blob ---")
    lines.append("sf_obj_font_chr:")
    for i, (name, cp, rows) in enumerate(ORDER):
        if rows is None:
            if cp not in kit:
                print(f"missing kit glyph ${cp:02X} for {name}", file=sys.stderr)
                sys.exit(1)
            rows = kit[cp]
        tile = bitmap_to_4bpp(rows)
        lbl = f"    ; tile {i}: {name}"
        lines.append(lbl)
        lines.append("    .byte " + ", ".join(f"${x:02X}" for x in tile[0:8]))
        lines.append("    .byte " + ", ".join(f"${x:02X}" for x in tile[8:16]))
        lines.append("    .byte " + ", ".join(f"${x:02X}" for x in tile[16:24]))
        lines.append("    .byte " + ", ".join(f"${x:02X}" for x in tile[24:32]))
    lines.append("sf_obj_font_chr_end:")
    lines.append("")
    lines.append(".endif ; SF_OBJ_TEXT_DATA_INC")
    out = "\n".join(lines) + "\n"
    Path(sys.argv[1]).write_text(out)
    print(f"wrote {sys.argv[1]} — {len(ORDER)} glyphs, {len(ORDER)*32} bytes")

if __name__ == "__main__":
    main()
