#!/usr/bin/env python3
"""Generate a shrinking-circle iris HDMA table set (WH0/WH1 per scanline).

Emits an .inc with N HDMA tables (DMAP mode 1: 2 registers written once each,
so one channel feeds WH0 $2126 + WH1 $2127 per scanline) tracing a circle that
shrinks from fully-open (covers the screen) to a point, centred on the screen.

Window is used with the "mask OUTSIDE the band" selectors, so the [L,R] band
each scanline = the VISIBLE (un-masked) interior of the circle; empty lines
(above/below the circle) get L=255,R=0 => empty band => whole line masked.

HDMA line-count encoding: a count byte then data.
  bit7=1 (continuous): the next (count) scanlines each read their OWN [WH0,WH1].
  bit7=0 (repeat):     ONE [WH0,WH1] pair repeats for (count) scanlines.
  count 1..127; a $00 byte terminates the channel.
Empty (masked) runs are emitted as repeat entries so small circles stay tiny.
"""
import math, sys

CX, CY = 128, 112          # screen centre (256x224)
LINES = 224
RMAX = 172                 # covers the corners: sqrt(128^2+112^2)=170.1
N = 30                     # close steps (1 per frame -> ~30-frame close)

def half_width(r, dy):
    d = r*r - dy*dy
    if d < 0:
        return None
    return int(round(math.sqrt(d)))

def line_band(r, y):
    """Return (WH0,WH1) for scanline y at radius r. Empty -> (255,0)."""
    dy = y - CY
    hw = half_width(r, dy)
    if hw is None or hw <= 0:
        return (255, 0)
    L = CX - hw
    R = CX + hw
    L = max(0, min(255, L))
    R = max(0, min(255, R))
    if L >= R:
        return (255, 0)
    return (L, R)

def encode_table(r):
    """Return list of bytes for one HDMA table (run-length optimised)."""
    lines = [line_band(r, y) for y in range(LINES)]
    out = []
    i = 0
    while i < LINES:
        j = i
        # run of identical pairs -> repeat mode (bit7=0)
        while j+1 < LINES and lines[j+1] == lines[i] and (j - i) < 126:
            j += 1
        run = j - i + 1
        if run >= 2:
            out.append(run & 0x7F)          # repeat: bit7=0
            out.append(lines[i][0]); out.append(lines[i][1])
            i = j + 1
        else:
            # continuous run of distinct pairs (bit7=1)
            k = i
            while k < LINES and (k - i) < 127:
                # stop the continuous run if a >=2 repeat starts at k
                if k+1 < LINES and lines[k+1] == lines[k]:
                    if k > i:
                        break
                k += 1
            cnt = k - i
            out.append(0x80 | (cnt & 0x7F))
            for m in range(i, k):
                out.append(lines[m][0]); out.append(lines[m][1])
            i = k
    out.append(0x00)                        # terminator
    return out

def radius_for_step(step):
    # eased radius shrink: step 0 = RMAX (fully open, no mask), step N-1 = 0.
    # t^1.5 drops fast early (blows through the off-screen "covers the corners"
    # phase in a few steps) then slows near the point-close — so most frames
    # show the circle actually shrinking on-screen.
    t = (N - 1 - step) / (N - 1)
    return RMAX * (t ** 1.5)

def main(out_path):
    tables = [encode_table(radius_for_step(s)) for s in range(N)]
    total = sum(len(t) for t in tables)
    lines = []
    lines.append("; Generated by tools/gen_iris_table.py — DO NOT EDIT BY HAND")
    lines.append("; cmd: gen_iris_table.py  (screen-centred shrinking-circle iris)")
    lines.append(f"; {N} HDMA tables, WH0/WH1 per scanline (DMAP mode $01), centre "
                 f"({CX},{CY}), Rmax={RMAX}. {total} bytes total.")
    lines.append("; A frame binds ONE allocated HDMA channel to iris_step_N with")
    lines.append("; BBAD=$26 ($2126 WH0) + DMAP=$01; window masks layers OUTSIDE the")
    lines.append("; band, so the [L,R] pair is the visible circle interior per line.")
    lines.append("")
    lines.append(f"IRIS_STEPS = {N}")
    lines.append("")
    for s, t in enumerate(tables):
        lines.append(f"iris_step_{s}:")
        for off in range(0, len(t), 16):
            chunk = t[off:off+16]
            lines.append("    .byte " + ", ".join(f"${b:02X}" for b in chunk))
    lines.append("")
    lines.append("; step -> table address (index with step*2)")
    lines.append("iris_step_tbl:")
    for s in range(N):
        lines.append(f"    .addr iris_step_{s}")
    lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}: {N} tables, {total} data bytes")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "iris.inc")
