#!/usr/bin/env python3
# =============================================================================
# provenance_check.py — the reproducible-assets / provenance gate (CI-blocking).
# =============================================================================
# The clean-room high-risk control. Unlike the name wordlist (a non-exhaustive
# tripwire — see tools/cleanroom_check.sh), this gate is COMPLETE by construction:
# it enumerates EVERY committed binary/asset blob and every large `.byte`/`.word`
# data table, then proves each one is either
#
#   (1) REPRODUCIBLE  — regenerated byte-for-byte from a committed generator
#                       (the manifest declares the command; the gate re-runs it
#                       into a throwaway sandbox copy and diffs), OR
#   (2) THIRD-PARTY   — registered as vendored, with a matching NOTICE entry, OR
#   (3) ATTESTED      — a small allowlist of known-non-regenerable-but-attributed
#                       blobs (e.g. the TAD example song set), each carrying a
#                       provenance note, OR
#   (4) ARTIFACT      — a committed verification render/screenshot (proof of a
#                       build, not a shipping game asset).
#
# Any enumerated blob with NO manifest entry FAILS. That is the rip-detector:
# an opaque blob someone dropped in with no generator and no attribution cannot
# pass, no matter what it is named. A name denylist can never be complete; "only
# assets we generate or properly attribute ship" CAN.
#
# The manifest is tools/provenance_manifest.toml (the single source of truth for
# what ships and why). This script enforces it.
#
# Usage:  python3 tools/provenance_check.py [tree_root]
#         python3 tools/provenance_check.py --list           # show coverage
# Exit 0 = every blob accounted for + every reproducible blob reproduced.
# Any uncovered blob, failed reproduction, or broken attribution chain -> exit 1.
# =============================================================================
from __future__ import annotations

import argparse
import fnmatch
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover - fallback for older interpreters
    try:
        import tomli as tomllib  # type: ignore
    except ModuleNotFoundError:
        tomllib = None

# --- What counts as a "blob the gate must account for" -----------------------
# Binary/asset extensions (rip risk: copied art, ripped maps, music).
BLOB_EXTS = {
    ".bin", ".zip", ".png", ".chr", ".pal", ".spc", ".brr", ".rsn",
    ".mid", ".gif", ".bmp", ".jpg", ".jpeg", ".wav", ".vgm", ".nsf",
}
# A `.inc` is a "data table" (and thus rip-risk, e.g. a ripped tilemap dumped to
# .byte) once it carries more than this many .byte/.word data lines.
DATA_TABLE_MIN_ROWS = 20

# Directories never enumerated (build output, fetched caches, VCS, python cruft).
SKIP_DIRS = {".git", "build", "Mesen", "__pycache__", ".pytest_cache",
             "node_modules", ".mypy_cache"}


def _iter_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            yield Path(dirpath) / name


def _is_data_table_inc(path: Path) -> bool:
    if path.suffix.lower() != ".inc":
        return False
    rows = 0
    try:
        with path.open("r", errors="ignore") as fh:
            for line in fh:
                s = line.lstrip()
                if s.startswith(".byte") or s.startswith(".word") or \
                   s.startswith(".dword") or s.startswith(".res "):
                    rows += 1
                    if rows > DATA_TABLE_MIN_ROWS:
                        return True
    except OSError:
        return False
    return False


def enumerate_blobs(root: Path) -> list[str]:
    """Every committed blob the gate must account for, as posix rel-paths."""
    out = []
    for f in _iter_files(root):
        rel = f.relative_to(root).as_posix()
        if f.suffix.lower() in BLOB_EXTS:
            out.append(rel)
        elif _is_data_table_inc(f):
            out.append(rel)
    return sorted(out)


def load_manifest(root: Path) -> dict:
    mpath = root / "tools" / "provenance_manifest.toml"
    if not mpath.exists():
        sys.stderr.write(
            f"provenance: FAIL — manifest not found at {mpath}.\n"
            "Every shipping blob must be registered there.\n")
        sys.exit(1)
    if tomllib is None:
        sys.stderr.write(
            "provenance: FAIL — no TOML parser (need Python 3.11+ or `pip install tomli`).\n")
        sys.exit(1)
    with mpath.open("rb") as fh:
        return tomllib.load(fh)


def _match_entry(rel: str, entries: list[dict]) -> dict | None:
    """First manifest entry whose `path` glob matches rel."""
    for e in entries:
        if fnmatch.fnmatch(rel, e["path"]):
            return e
    return None


def _notice_text(root: Path) -> str:
    n = root / "NOTICE"
    return n.read_text(errors="ignore") if n.exists() else ""


def _regenerate_and_diff(root: Path, entry: dict, covered_rels: list[str]) -> list[str]:
    """Run entry['regenerate'] in a sandbox copy of the kit; diff its outputs
    (entry['produces'] globs) byte-for-byte against the committed tree.
    Returns a list of failure strings (empty = reproduced exactly)."""
    fails: list[str] = []
    cmd = entry["regenerate"]
    produces = entry.get("produces") or [entry["path"]]
    with tempfile.TemporaryDirectory(prefix="prov_regen_") as tmp:
        sandbox = Path(tmp) / "kit"
        # Copy the whole tree (cheap relative to a build); skip heavy caches.
        shutil.copytree(
            root, sandbox,
            ignore=shutil.ignore_patterns(*SKIP_DIRS, "*.sfc", "*.o"))
        env = dict(os.environ)
        env["PYTHONPATH"] = "." + os.pathsep + env.get("PYTHONPATH", "")
        proc = subprocess.run(
            cmd, shell=True, cwd=sandbox, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if proc.returncode != 0:
            tail = proc.stdout.decode(errors="ignore")[-800:]
            fails.append(
                f"  REGEN-FAILED [{entry['path']}]: `{cmd}` exited "
                f"{proc.returncode}\n{tail}")
            return fails
        # Diff every produced file.
        for prod_glob in produces:
            matched = [r for r in covered_rels if fnmatch.fnmatch(r, prod_glob)]
            if not matched:
                matched = [prod_glob]
            for rel in matched:
                committed = root / rel
                regenerated = sandbox / rel
                if not regenerated.exists():
                    fails.append(
                        f"  REGEN-MISSING [{rel}]: generator did not produce it")
                    continue
                if committed.read_bytes() != regenerated.read_bytes():
                    fails.append(
                        f"  REGEN-MISMATCH [{rel}]: committed bytes differ from "
                        f"`{cmd}` output (asset is NOT reproducible — stale or hand-edited)")
    return fails


def check(root: Path, do_regen: bool = True) -> int:
    manifest = load_manifest(root)
    entries = manifest.get("asset", [])
    blobs = enumerate_blobs(root)

    fails: list[str] = []
    uncovered: list[str] = []
    notice = _notice_text(root)

    # Phase 1 — coverage: every enumerated blob must match a manifest entry.
    coverage: dict[str, dict] = {}
    for rel in blobs:
        entry = _match_entry(rel, entries)
        if entry is None:
            uncovered.append(rel)
        else:
            coverage[rel] = entry

    if uncovered:
        fails.append(
            "OPAQUE BLOBS WITH NO PROVENANCE (the rip-detector tripped):")
        for rel in uncovered:
            fails.append(f"  UNREGISTERED: {rel}")
        fails.append(
            "  -> Either register a generator (kind=generator, with `regenerate`),\n"
            "     attribute it as third-party (kind=third-party, NOTICE entry), or\n"
            "     attest it (kind=attested / kind=artifact) in tools/provenance_manifest.toml.")

    # Phase 2 — per-entry verification.
    regen_done: set[int] = set()  # dedupe entries that produce many files
    for rel, entry in coverage.items():
        kind = entry.get("kind")
        if kind == "generator":
            if do_regen and "regenerate" in entry:
                eid = id(entry)
                if eid not in regen_done:
                    regen_done.add(eid)
                    fails.extend(_regenerate_and_diff(root, entry, blobs))
            elif "regenerate" not in entry:
                # Coverage-only generator: require the generator file to exist
                # AND the asset to carry a generated-by attestation header.
                gen = entry.get("generator")
                if not gen or not (root / gen).exists():
                    fails.append(
                        f"  GENERATOR-MISSING [{rel}]: declared generator "
                        f"'{gen}' not found in tree")
        elif kind == "third-party":
            token = entry.get("notice_token")
            if not token:
                fails.append(
                    f"  THIRD-PARTY-NO-TOKEN [{rel}]: entry must name a "
                    "notice_token to verify against NOTICE")
            elif token not in notice:
                fails.append(
                    f"  THIRD-PARTY-UNATTRIBUTED [{rel}]: '{token}' not found "
                    "in NOTICE (attribution chain broken)")
        elif kind in ("attested", "artifact"):
            if not entry.get("note"):
                fails.append(
                    f"  ATTESTED-NO-NOTE [{rel}]: kind={kind} requires a `note` "
                    "explaining provenance")
        else:
            fails.append(
                f"  BAD-KIND [{rel}]: unknown kind={kind!r} in manifest entry")

    # Report.
    if fails:
        sys.stderr.write("\n".join(fails) + "\n")
        n_other = len(fails) - (1 if uncovered else 0) - len(uncovered) - (1 if uncovered else 0)
        sys.stderr.write(
            f"\nprovenance: FAIL — {len(uncovered)} unregistered blob(s) + "
            "other findings above.\n")
        return 1

    print(f"provenance: clean — {len(blobs)} blob(s) accounted for "
          f"({sum(1 for e in coverage.values() if e.get('kind') == 'generator')} "
          f"generated, "
          f"{sum(1 for e in coverage.values() if e.get('kind') == 'third-party')} third-party, "
          f"{sum(1 for e in coverage.values() if e.get('kind') == 'attested')} attested, "
          f"{sum(1 for e in coverage.values() if e.get('kind') == 'artifact')} artifact)"
          + ("" if do_regen else " [--no-regen: reproduction NOT verified]"))
    return 0


def list_coverage(root: Path) -> int:
    manifest = load_manifest(root)
    entries = manifest.get("asset", [])
    for rel in enumerate_blobs(root):
        e = _match_entry(rel, entries)
        tag = e["kind"] if e else "UNREGISTERED"
        print(f"{tag:14s}  {rel}")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("root", nargs="?", default=".",
                    help="tree root to scan (default: cwd)")
    ap.add_argument("--list", action="store_true",
                    help="print coverage classification for every blob and exit")
    ap.add_argument("--no-regen", action="store_true",
                    help="skip the byte-for-byte regeneration step (coverage only)")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve()
    if args.list:
        return list_coverage(root)
    return check(root, do_regen=not args.no_regen)


if __name__ == "__main__":
    sys.exit(main())
