; rom-backing fixture — the VIOLATION arm. Byte-for-byte main_backed.asm with
; the two real claim sites removed, and nothing else changed.
;
; This is the shape of the bug it reproduces: rgb_gradient's `grad_tabs` during
; an earlier breaker build (2026-08-02) was generated by its asset tool,
; prerequisited in the Makefile and packed by the allocator, and no .asm file
; ever included it. Three HDMA channels streamed the neighbouring blob's bytes
; as COLDATA; the only symptom was a missing backdrop wash, and `make register`,
; `no_literals`, `width-check`, the allocator's own packing and the full pytest
; suite were all green.
;
; `make rom-unbacked` requires this file to be REFUSED, naming BOTH missing
; claims. A gate nobody has seen fail is not a gate.
.p816
.smart

.segment "BANK1"
; --- fixture_blob's claim site is GONE (the plain case) ---------------------

; --- fixture_tiles' claim site is GONE (the templated case) ----------------

; fixture_extern still has none, and still must be accepted: the missing sites
; must be reported WITHOUT the declared exemption being swept up with them.
