#!/usr/bin/env python3
"""
gradient_lut.py — Easing LUT Generator for Phase 9 RGB Gradient Engine

Generates 4 × 32-entry easing lookup tables for COLDATA intensity mapping.
Each table maps a linear 5-bit intensity (0-31) to an eased output (0-31).

Curves:
  0 = Linear (identity)
  1 = Ease-in (accelerating: x²/31)
  2 = Ease-out (decelerating: 31-(31-x)²/31)
  3 = Ease-in-out (S-curve: 3t²-2t³ scaled to 0-31)

Output: ca65 .byte directives for ROM embedding.
Total size: 128 bytes (4 curves × 32 entries).
"""

import math
import sys
import os


def generate_linear(n=32):
    """Identity mapping: output = input."""
    return list(range(n))


def generate_ease_in(n=32):
    """Accelerating curve: y = x²/31."""
    return [round(x * x / (n - 1)) for x in range(n)]


def generate_ease_out(n=32):
    """Decelerating curve: y = 31 - (31-x)²/31."""
    max_val = n - 1
    return [round(max_val - (max_val - x) ** 2 / max_val) for x in range(n)]


def generate_ease_in_out(n=32):
    """S-curve: cubic Hermite 3t²-2t³ scaled to 0-31."""
    max_val = n - 1
    result = []
    for x in range(n):
        t = x / max_val  # normalize to 0-1
        s = 3 * t * t - 2 * t * t * t  # smoothstep
        result.append(round(s * max_val))
    return result


def format_table(name, values, entries_per_line=8):
    """Format a table as ca65 .byte directives."""
    lines = [f"; {name}"]
    for i in range(0, len(values), entries_per_line):
        chunk = values[i:i + entries_per_line]
        line = "    .byte " + ", ".join(f"${v:02X}" for v in chunk)
        lines.append(line)
    return "\n".join(lines)


def generate_inc_file():
    """Generate the full .inc file content."""
    linear = generate_linear()
    ease_in = generate_ease_in()
    ease_out = generate_ease_out()
    ease_in_out = generate_ease_in_out()

    lines = [
        "; =============================================================================",
        "; gradient_ease_lut.inc — Easing LUT for RGB Gradient Engine (Phase 9)",
        "; =============================================================================",
        "; Generated by toolchain/gradient_lut.py — DO NOT EDIT MANUALLY",
        ";",
        "; 4 curves × 32 entries = 128 bytes total.",
        "; Index with: lda f:gradient_ease_lut + (easing_type * 32), x",
        ";   where X = linear intensity (0-31), A = eased intensity (0-31)",
        ";",
        "; Curve IDs:",
        ";   0 = Linear (identity)",
        ";   1 = Ease-in (accelerating: x²/31)",
        ";   2 = Ease-out (decelerating: 31-(31-x)²/31)",
        ";   3 = Ease-in-out (S-curve: 3t²-2t³)",
        "; =============================================================================",
        "",
        "gradient_ease_lut:",
        "",
        format_table("Curve 0: Linear (identity)", linear),
        "",
        format_table("Curve 1: Ease-in (x²/31)", ease_in),
        "",
        format_table("Curve 2: Ease-out (31-(31-x)²/31)", ease_out),
        "",
        format_table("Curve 3: Ease-in-out (3t²-2t³)", ease_in_out),
        "",
    ]
    return "\n".join(lines)


def main():
    """Generate and write the easing LUT .inc file."""
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "engine", "gradient_ease_lut.inc"
    )

    if len(sys.argv) > 1:
        output_path = sys.argv[1]

    content = generate_inc_file()

    with open(output_path, "w") as f:
        f.write(content)
        f.write("\n")

    print(f"Generated easing LUT: {output_path} (128 bytes, 4 curves)")

    # Validate tables
    linear = generate_linear()
    ease_in = generate_ease_in()
    ease_out = generate_ease_out()
    ease_in_out = generate_ease_in_out()

    for name, table in [("linear", linear), ("ease_in", ease_in),
                         ("ease_out", ease_out), ("ease_in_out", ease_in_out)]:
        assert len(table) == 32, f"{name}: expected 32 entries, got {len(table)}"
        assert table[0] == 0, f"{name}: first entry should be 0, got {table[0]}"
        assert table[31] == 31, f"{name}: last entry should be 31, got {table[31]}"
        assert all(0 <= v <= 31 for v in table), f"{name}: values out of range"

    # Verify easing properties
    assert ease_in[8] < 8, f"ease_in[8]={ease_in[8]} should be < 8 (slower start)"
    assert ease_out[8] > 8, f"ease_out[8]={ease_out[8]} should be > 8 (faster start)"

    print("All validations passed.")


if __name__ == "__main__":
    main()
