"""
Phase 8A Task 8A.1: Mode 7 LUT Generators

Generates lookup tables for Mode 7 affine transform math:

  1. Sine LUT (512 entries, 1.7.8 signed fixed-point):
     sin_lut[i] = round(sin(i * pi / 256) * 256)  for i=0..511
     Values range from -256 to +256 (stored as signed 16-bit).
     Cosine is derived by indexing at offset +128 (quarter-period shift).

  2. Perspective Reciprocal LUT (224 entries, unsigned fixed-point):
     perspective_lut[d] = round((h << 8) / d)  for d=1..224
     Parameterized by viewer height h.

Both generators emit ca65-compatible .byte/.word directives in .inc files.
All fixed-point values use 1.7.8 format (1 sign bit, 7 integer bits, 8
fractional bits) for 16-bit compatibility with the 65816's native word size.

References:
  - docs/sprints/phase_8_mode7.md (Phase 8A spec)
  - engine/mode7_math.asm (consumer of these LUTs)
  - docs/superforge_cycle_budget_v0.1.md (cycle budget)
"""

from __future__ import annotations

import math
import struct
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Sine LUT Generator
# ---------------------------------------------------------------------------

def generate_sin_lut() -> list[int]:
    """Generate 512-entry sine lookup table in 1.7.8 signed fixed-point.

    sin_lut[i] = round(sin(i * pi / 256) * 256)

    Index mapping (512 entries = full circle):
      i=0   -> sin(0)        = 0
      i=64  -> sin(pi/4)     = ~181  (sin(45 deg) * 256)
      i=128 -> sin(pi/2)     = 256   (sin(90 deg) * 256)
      i=192 -> sin(3*pi/4)   = ~181
      i=256 -> sin(pi)       = 0
      i=320 -> sin(5*pi/4)   = ~-181
      i=384 -> sin(3*pi/2)   = -256
      i=448 -> sin(7*pi/4)   = ~-181

    Cosine lookup: cos(i) = sin_lut[(i + 128) & 0x1FF]

    Returns:
        List of 512 signed integers in range [-256, +256].
    """
    lut = []
    for i in range(512):
        angle = i * math.pi / 256.0
        value = round(math.sin(angle) * 256.0)
        # Clamp to valid range (should not exceed, but safety)
        # Note: sin(pi/2)*256 = 256 exactly, which is valid signed 16-bit
        value = max(-256, min(256, value))
        lut.append(value)
    return lut


def sin_lut_to_inc(lut: list[int], label: str = "sin_lut") -> str:
    """Convert sine LUT to ca65 .word directives (signed 16-bit).

    Each entry is a 16-bit signed value stored as a .word directive.
    Negative values are emitted as two's complement (e.g., -256 -> $FF00).

    Args:
        lut: List of 512 signed integers from generate_sin_lut().
        label: Assembly label for the table.

    Returns:
        String containing ca65-compatible assembly source.
    """
    lines = []
    lines.append(f"; Mode 7 Sine LUT — 512 entries, 1.7.8 signed fixed-point")
    lines.append(f"; Generated by toolchain/mode7_lut.py")
    lines.append(f"; sin_lut[i] = round(sin(i * pi / 256) * 256)")
    lines.append(f"; Cosine: index at (i + 128) & $1FF")
    lines.append(f";")
    lines.append(f"; Total size: 1024 bytes (512 entries x 2 bytes)")
    lines.append(f"")
    lines.append(f"{label}:")

    for i in range(0, len(lut), 8):
        chunk = lut[i:i + 8]
        words = []
        for v in chunk:
            if v < 0:
                v = v & 0xFFFF  # Two's complement for ca65
            words.append(f"${v:04X}")
        lines.append(f"    .word {', '.join(words)}    ; [{i}..{i + len(chunk) - 1}]")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Perspective Reciprocal LUT Generator
# ---------------------------------------------------------------------------

def generate_perspective_lut(viewer_height: int) -> list[int]:
    """Generate perspective reciprocal LUT for a given viewer height.

    perspective_lut[d] = round((h << 8) / d) for d=1..224

    This precomputes the per-scanline scale factor for Mode 7 perspective
    floor rendering. Larger values at small d (close to camera) produce
    wider scanline stretching; values decrease toward the horizon.

    Args:
        viewer_height: Viewer height in pixels (typically 64-128).

    Returns:
        List of 224 unsigned integers. Index 0 corresponds to d=1.
    """
    h_shifted = viewer_height << 8
    lut = []
    for d in range(1, 225):
        value = round(h_shifted / d)
        # Clamp to 16-bit unsigned
        value = min(value, 0xFFFF)
        lut.append(value)
    return lut


def perspective_lut_to_inc(
    lut: list[int],
    viewer_height: int,
    label: str = "perspective_lut",
) -> str:
    """Convert perspective LUT to ca65 .word directives (unsigned 16-bit).

    Args:
        lut: List of 224 unsigned integers from generate_perspective_lut().
        viewer_height: Viewer height used for generation (for comment).
        label: Assembly label for the table.

    Returns:
        String containing ca65-compatible assembly source.
    """
    lines = []
    lines.append(f"; Mode 7 Perspective Reciprocal LUT — 224 entries, unsigned 16-bit")
    lines.append(f"; Generated by toolchain/mode7_lut.py")
    lines.append(f"; perspective_lut[d-1] = round((h << 8) / d), h={viewer_height}")
    lines.append(f"; d=1..224 (scanline distance from horizon)")
    lines.append(f";")
    lines.append(f"; Total size: 448 bytes (224 entries x 2 bytes)")
    lines.append(f"")
    lines.append(f"{label}:")

    for i in range(0, len(lut), 8):
        chunk = lut[i:i + 8]
        words = [f"${v:04X}" for v in chunk]
        d_start = i + 1
        d_end = i + len(chunk)
        lines.append(f"    .word {', '.join(words)}    ; d={d_start}..{d_end}")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File Generation
# ---------------------------------------------------------------------------

def write_sin_lut_inc(output_path: Path | str) -> list[int]:
    """Generate sine LUT and write to .inc file.

    Args:
        output_path: Path for the output .inc file.

    Returns:
        The generated LUT (for testing).
    """
    lut = generate_sin_lut()
    content = sin_lut_to_inc(lut)
    Path(output_path).write_text(content)
    return lut


def write_perspective_lut_inc(
    output_path: Path | str,
    viewer_height: int = 64,
) -> list[int]:
    """Generate perspective reciprocal LUT and write to .inc file.

    Args:
        output_path: Path for the output .inc file.
        viewer_height: Viewer height in pixels (default 64).

    Returns:
        The generated LUT (for testing).
    """
    lut = generate_perspective_lut(viewer_height)
    content = perspective_lut_to_inc(lut, viewer_height)
    Path(output_path).write_text(content)
    return lut


# ---------------------------------------------------------------------------
# Depth-to-Scanline Inverse LUT Generator (Phase 12D)
# ---------------------------------------------------------------------------

def generate_depth_to_scanline_lut(
    viewer_height: int = 50,
    horizon: int = 57,
    max_scanline: int = 224,
) -> list[int]:
    """Generate inverse perspective LUT: world depth → screen scanline.

    For a vehicle at world-pixel distance D ahead of the camera, this LUT
    gives the screen scanline where it should appear.

    Formula: scanline(D) = horizon + (height * 256) / D

    This is the mathematical inverse of the perspective reciprocal table.
    Built for a fixed camera height — if height changes dynamically (e.g.
    Phase 12G Tommy Moe), this LUT must be regenerated.

    Args:
        viewer_height: Camera height in world pixels (default 50, racing-genre tuning).
        horizon: Horizon scanline (default 57 for height=50).
        max_scanline: Bottom of visible floor (default 224).

    Returns:
        List of 256 integers. Each entry is a scanline (0-223) or 0xFF
        if the depth is behind camera, too close (below screen), or too far.
    """
    h_factor = viewer_height * 256
    lut = []
    for d in range(256):
        if d == 0:
            # At camera position — not visible
            lut.append(0xFF)
            continue
        scanline = horizon + h_factor // d
        if scanline < horizon or scanline > max_scanline:
            lut.append(0xFF)
        else:
            lut.append(scanline)
    return lut


def depth_to_scanline_lut_to_inc(
    lut: list[int],
    viewer_height: int,
    horizon: int,
    label: str = "depth_to_scanline",
) -> str:
    """Convert depth-to-scanline LUT to ca65 .word directives.

    Each entry is 2 bytes (16-bit) for uniform indexing: scanline or $00FF.

    Args:
        lut: 256 entries from generate_depth_to_scanline_lut().
        viewer_height: Height used (for comment).
        horizon: Horizon scanline (for comment).
        label: Assembly label.

    Returns:
        ca65-compatible assembly source string.
    """
    lines = []
    lines.append(f"; Depth-to-Scanline Inverse LUT — 256 entries × 2 bytes = 512 bytes")
    lines.append(f"; Generated by toolchain/mode7_lut.py")
    lines.append(f"; depth_to_scanline[d] = horizon + (h * 256) / d")
    lines.append(f"; h={viewer_height}, horizon={horizon}")
    lines.append(f"; $00FF = not visible (behind camera, too close, or too far)")
    lines.append(f";")
    lines.append(f"; Total size: 512 bytes (256 entries x 2 bytes)")
    lines.append(f"")
    lines.append(f"{label}:")

    for i in range(0, len(lut), 8):
        chunk = lut[i:i + 8]
        words = [f"${v:04X}" for v in chunk]
        lines.append(f"    .word {', '.join(words)}    ; d={i}..{i + len(chunk) - 1}")

    lines.append("")
    return "\n".join(lines)


def write_depth_to_scanline_inc(
    output_path: Path | str = "assets/racing/depth_to_scanline.inc",
    viewer_height: int = 50,
    horizon: int = 57,
    max_scanline: int = 224,
) -> list[int]:
    """Generate depth-to-scanline LUT and write to .inc file.

    Returns the generated LUT (for testing).
    """
    lut = generate_depth_to_scanline_lut(viewer_height, horizon, max_scanline)
    content = depth_to_scanline_lut_to_inc(lut, viewer_height, horizon)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content)
    return lut


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

def main() -> None:
    """Generate both LUT .inc files to the engine/ directory."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate Mode 7 lookup tables for SuperForge"
    )
    parser.add_argument(
        "--sin-output",
        default="engine/mode7_sin_lut.inc",
        help="Output path for sine LUT .inc file (default: engine/mode7_sin_lut.inc)",
    )
    parser.add_argument(
        "--perspective-output",
        default="engine/mode7_perspective_lut.inc",
        help="Output path for perspective LUT .inc file "
             "(default: engine/mode7_perspective_lut.inc)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=64,
        help="Viewer height for perspective LUT in pixels (default: 64)",
    )

    args = parser.parse_args()

    sin_lut = write_sin_lut_inc(args.sin_output)
    print(f"Wrote sine LUT ({len(sin_lut)} entries) to {args.sin_output}")

    persp_lut = write_perspective_lut_inc(args.perspective_output, args.height)
    print(
        f"Wrote perspective LUT ({len(persp_lut)} entries, h={args.height}) "
        f"to {args.perspective_output}"
    )


if __name__ == "__main__":
    main()
