"""
Convert a full 1024x1024 Mode 7 map PNG into ca65 .inc data.

Input: 1024x1024 RGB PNG (128x128 tiles at 8x8 pixels each)
Output: ca65 .inc file with interleaved VRAM data + palette

The converter:
1. Splits the image into 8x8 tiles
2. Deduplicates identical tiles
3. Builds a 128x128 tilemap of tile indices
4. Extracts the palette (RGB → SNES BGR555)
5. Emits ca65 .byte directives for the interleaved VRAM + palette
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path
from PIL import Image

from toolchain.mode7_assets import rgb_to_bgr555


def convert_map_png(image_path: str) -> tuple[bytes, bytes, bytes]:
    """Convert a full map PNG to Mode 7 tileset + tilemap + palette.

    Returns (tile_data, tilemap, palette) ready for interleaving.
    """
    img = Image.open(image_path).convert("RGB")

    if img.width != 1024 or img.height != 1024:
        raise ValueError(
            f"Expected 1024x1024 image, got {img.width}x{img.height}"
        )

    pixels = img.load()

    # Build palette from unique colors
    color_map: dict[tuple[int, int, int], int] = {}
    palette_rgb: list[tuple[int, int, int]] = []

    # Extract tiles and deduplicate
    unique_tiles: dict[tuple[int, ...], int] = {}
    tile_pixel_data: list[list[int]] = []  # list of 64-byte tile data
    tilemap: list[int] = []

    for ty in range(128):
        for tx in range(128):
            tile_indices = []
            for py in range(8):
                for px in range(8):
                    r, g, b = pixels[tx * 8 + px, ty * 8 + py]
                    color = (r, g, b)
                    if color not in color_map:
                        if len(palette_rgb) >= 256:
                            raise ValueError("More than 256 unique colors")
                        color_map[color] = len(palette_rgb)
                        palette_rgb.append(color)
                    tile_indices.append(color_map[color])

            tile_key = tuple(tile_indices)
            if tile_key not in unique_tiles:
                if len(unique_tiles) >= 256:
                    raise ValueError(
                        f"More than 256 unique tiles at ({tx}, {ty})"
                    )
                unique_tiles[tile_key] = len(unique_tiles)
                tile_pixel_data.append(tile_indices)

            tilemap.append(unique_tiles[tile_key])

    print(f"Unique tiles: {len(unique_tiles)}")
    print(f"Unique colors: {len(palette_rgb)}")

    # Build 8bpp tile data (64 bytes per tile, padded to 256 tiles)
    tile_data = bytearray()
    for tile in tile_pixel_data:
        tile_data.extend(tile)
    # Pad to 256 tiles
    while len(tile_data) < 16384:
        tile_data.append(0)

    # Build tilemap (128x128 = 16384 bytes)
    tilemap_bytes = bytes(tilemap)

    # Build BGR555 palette (256 colors x 2 bytes)
    palette_bytes = bytearray()
    for i in range(256):
        if i < len(palette_rgb):
            r, g, b = palette_rgb[i]
            bgr = rgb_to_bgr555(r, g, b)
        else:
            bgr = 0
        palette_bytes.extend(struct.pack("<H", bgr))

    return bytes(tile_data), tilemap_bytes, bytes(palette_bytes)


def emit_asm(tile_data: bytes, tilemap: bytes, palette: bytes,
             output_path: str) -> None:
    """Emit ca65-compatible .inc file with Mode 7 data."""
    lines = []
    lines.append("; =============================================================================")
    lines.append("; mode7_airship_data.inc — Generated from airfield_map_v2.png")
    lines.append("; =============================================================================")
    lines.append("; Auto-generated by toolchain/mode7_map_converter.py")
    lines.append("; DO NOT EDIT — regenerate from the source PNG")
    lines.append(";")
    lines.append("; Must NOT have .p816/.smart (included into parent)")
    lines.append("; =============================================================================")
    lines.append("")

    # Tile data — 8bpp, 64 bytes per tile
    # Find actual tile count (non-zero tiles)
    actual_tiles = 0
    for t in range(256):
        start = t * 64
        if any(tile_data[start:start + 64]):
            actual_tiles = t + 1

    lines.append(f"; Tile pixel data: {actual_tiles} tiles x 64 bytes = "
                 f"{actual_tiles * 64} bytes (8bpp, 8x8)")
    lines.append("airship_tiles:")

    # Only emit actual tiles (not the full 256-tile pad)
    for t in range(actual_tiles):
        lines.append(f"; --- Tile {t} ---")
        for row in range(8):
            offset = t * 64 + row * 8
            chunk = tile_data[offset:offset + 8]
            hex_bytes = ", ".join(f"${b:02X}" for b in chunk)
            lines.append(f"    .byte {hex_bytes}")

    lines.append("")
    lines.append(f"AIRSHIP_TILES_COUNT = {actual_tiles}")
    lines.append(f"AIRSHIP_TILE_SIZE   = 64")
    lines.append(f"AIRSHIP_TILES_SIZE  = AIRSHIP_TILES_COUNT * AIRSHIP_TILE_SIZE")
    lines.append("")

    # Tilemap — 128x128 = 16384 bytes
    lines.append("; 128x128 tilemap (16384 bytes)")
    lines.append("airship_tilemap_full:")
    for row in range(128):
        offset = row * 128
        row_data = tilemap[offset:offset + 128]
        # Emit in chunks of 16 for readability
        for col_start in range(0, 128, 16):
            chunk = row_data[col_start:col_start + 16]
            hex_bytes = ", ".join(f"${b:02X}" for b in chunk)
            if col_start == 0:
                lines.append(f"    ; Row {row}")
            lines.append(f"    .byte {hex_bytes}")

    lines.append("")
    lines.append("AIRSHIP_TILEMAP_FULL_SIZE = 16384")
    lines.append("")

    # Palette — only emit used colors
    used_colors = 0
    for i in range(256):
        word = struct.unpack_from("<H", palette, i * 2)[0]
        if word != 0 or i == 0:
            used_colors = i + 1

    lines.append(f"; CGRAM palette: {used_colors} colors x 2 bytes BGR555")
    lines.append("airship_palette:")
    for i in range(used_colors):
        word = struct.unpack_from("<H", palette, i * 2)[0]
        lines.append(f"    .word ${word:04X}    ; color {i}")

    lines.append("")
    lines.append(f"AIRSHIP_PALETTE_SIZE = {used_colors * 2}")
    lines.append(f"AIRSHIP_PALETTE_COLORS = {used_colors}")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {output_path} ({len(lines)} lines)")


def emit_binary(tile_data: bytes, tilemap: bytes, palette: bytes,
                output_dir: str) -> None:
    """Emit binary files for .incbin usage."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Find actual tile count
    actual_tiles = 0
    for t in range(256):
        start = t * 64
        if any(tile_data[start:start + 64]):
            actual_tiles = t + 1

    # Write tile data (only used tiles)
    tiles_path = out / "m7_tiles.bin"
    with open(tiles_path, "wb") as f:
        f.write(tile_data[:actual_tiles * 64])
    print(f"Wrote {tiles_path} ({actual_tiles * 64} bytes, {actual_tiles} tiles)")

    # Write full tilemap
    tilemap_path = out / "m7_tilemap.bin"
    with open(tilemap_path, "wb") as f:
        f.write(tilemap)
    print(f"Wrote {tilemap_path} ({len(tilemap)} bytes)")

    # Write palette (only used colors)
    used_colors = 0
    for i in range(256):
        word = struct.unpack_from("<H", palette, i * 2)[0]
        if word != 0 or i == 0:
            used_colors = i + 1

    palette_path = out / "m7_palette.bin"
    with open(palette_path, "wb") as f:
        f.write(palette[:used_colors * 2])
    print(f"Wrote {palette_path} ({used_colors * 2} bytes, {used_colors} colors)")

    # Write a small .inc header with constants and .incbin directives
    inc_path = out / "mode7_airship_data.inc"
    lines = [
        "; =============================================================================",
        "; mode7_airship_data.inc — Generated from airfield_map_v2.png",
        "; =============================================================================",
        "; Auto-generated by toolchain/mode7_map_converter.py",
        "; Uses .incbin for bulk data to keep assembly fast",
        "; Must NOT have .p816/.smart (included into parent)",
        "; =============================================================================",
        "",
        f"AIRSHIP_TILES_COUNT = {actual_tiles}",
        f"AIRSHIP_TILE_SIZE   = 64",
        f"AIRSHIP_TILES_SIZE  = {actual_tiles * 64}",
        f"AIRSHIP_PALETTE_COLORS = {used_colors}",
        f"AIRSHIP_PALETTE_SIZE = {used_colors * 2}",
        "",
        "airship_tiles:",
        '    .incbin "m7_tiles.bin"',
        "",
        "airship_tilemap_full:",
        '    .incbin "m7_tilemap.bin"',
        "",
        "airship_palette:",
        '    .incbin "m7_palette.bin"',
        "",
    ]
    with open(inc_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {inc_path}")


def load_or_convert_mode7(png_path: str) -> dict:
    """Load a 1024x1024 Mode 7 map PNG and produce the full-format
    payload consumed by the parent build pipeline's Mode 7 emit
    branch.

    Return shape (post-16-3-0 convention):
        {
            "format": "full",                   # vs compact-format demos
            "vram_interleaved": bytes(32768),   # pre-interleaved blob
            "palette": bytes(512),              # BGR555 CGRAM data
            "tile_count": int,                  # unique tiles in tileset
            "source_path": str,                 # for diagnostics
        }

    Matches Brad's dizworld build-time-interleave / DMA-at-runtime
    pattern (dizworld.s DMAs a pre-interleaved blob rather than
    CPU-looping the interleave at boot). Faster + cleaner build surface.

    Uses convert_map_png (tile dedup + tilemap build + palette extract)
    then toolchain/mode7_assets.py::interleave_mode7_data.
    """
    from toolchain.mode7_assets import interleave_mode7_data

    tile_data, tilemap, palette = convert_map_png(png_path)
    interleaved = interleave_mode7_data(tilemap, tile_data)
    # tile_data is always padded to 16384 bytes (256 × 64) inside
    # convert_map_png. The *unique* tile count is printed to stdout by
    # that function but not returned; field here is the padded count.
    tile_count = len(tile_data) // 64  # always 256 post-padding

    if len(interleaved) != 32768:
        raise RuntimeError(
            f"Mode 7 VRAM blob is {len(interleaved)} bytes, expected 32768. "
            f"Source: {png_path}"
        )
    if len(palette) != 512:
        raise RuntimeError(
            f"Mode 7 palette is {len(palette)} bytes, expected 512. "
            f"Source: {png_path}"
        )

    return {
        "format": "full",
        "vram_interleaved": interleaved,
        "palette": palette,
        "tile_count": tile_count,
        "source_path": png_path,
    }


def main():
    image_path = sys.argv[1] if len(sys.argv) > 1 else "build/airfield_map_v2.png"
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "build"

    tile_data, tilemap, palette = convert_map_png(image_path)
    emit_binary(tile_data, tilemap, palette, output_dir)

    from toolchain.mode7_assets import bgr555_to_rgb
    print(f"\nPalette ({sum(1 for i in range(256) if struct.unpack_from('<H', palette, i*2)[0] != 0 or i == 0)} colors):")
    for i in range(256):
        word = struct.unpack_from("<H", palette, i * 2)[0]
        if word != 0 or i == 0:
            r, g, b = bgr555_to_rgb(word)
            print(f"  {i}: ${word:04X} -> RGB({r},{g},{b})")


if __name__ == "__main__":
    main()
